### ISSUE TITLE
[BUG] 挂载磁盘到 windows系显示挂载错误

### ISSUE THREAD

**Issue by saltfishh** [yunionio/cloudpods#16997]
**问题描述/What happened**:
磁盘无法挂载到 windows 主机上
**环境/Environment**:

- OS (e.g. `cat /etc/os-release`):
  + centos7.9
- Kernel (e.g. `uname -a`):
  + 3.10.0-1160
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
  + DELL R730
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):
  + v3.10.0

```bash
+-----------------+----------------------------------------------+
|      Field      |                    Value                     |
+-----------------+----------------------------------------------+
| ansible         | release/3.10(c0920a499323042602)             |
| cloudevent      | release/3.10(c0920a499323042602)             |
| cloudid         | release/3.10(c0920a499323042603)             |
| cloudmeta       | ci/ucloud-basic-data-support(aedc811)        |
| cloudmon        | release/3.10(c0920a499323042603)             |
| cloudproxy      | release/3.10(c0920a499323042602)             |
| compute_v2      | release/3.10(c0920a499323042603)             |
| devtool         | release/3.10(c0920a499323042602)             |
| etcd            | {"etcdserver":"3.4.6","etcdcluster":"3.4.0"} |
| identity        | release/3.10(c0920a499323042602)             |
| image           | release/3.10(c0920a499323042602)             |
| influxdb        | 404 page not found                           |
| k8s             | heads/v3.10.0-20230425.2(8962b3823042602)    |
| log             | release/3.10(c0920a499323042602)             |
| monitor         | release/3.10(c0920a499323042603)             |
| notify          | release/3.10(c0920a499323042602)             |
| scheduledtask   | release/3.10(c0920a499323042603)             |
| scheduler       | release/3.10(c0920a499323042602)             |
| torrent-tracker | <title>Not Found</title>                     |
| webconsole      | release/3.10(c0920a499323042602)             |
| yunionconf      | release/3.10(c0920a499323042602)             |
+-----------------+----------------------------------------------+

```

故障描述:
- 磁盘挂载到 win10 或 winserver 2016时, 显示 `挂载磁盘失败`. 以下为 该事件的日志:

```bash
{
    "__reason__": {
        "reason": {
            "__reason__": "runtime error: invalid memory address or nil pointer dereference",
            "__stage__": "on_sync_complete",
            "__status__": "error"
        },
        "stage": "on_sync_complete"
    },
    "__stage__": "on_sync_config_complete",
    "__status__": "error",
    "__task_name__": "GuestSyncConfTask"
}
```

- 挂载到 Linux 上正常.

- 存储为 `本地存储` . 挂载点为 `/opt/cloud/workspace/temp-bind/data/storage`
启用状态
启用
存储类型
GPFS
介质类型
机械盘

**Comment by saltfishh** [comment]
同步配置时, 也会出错.

```bash
{
    "__reason__": "runtime error: invalid memory address or nil pointer dereference",
    "__stage__": "on_sync_complete",
    "__status__": "error"
}
```

**Comment by saltfishh** [comment]
挂载磁盘时, `host` pod 日志:

```bash
[info 2023-05-10 06:03:22 modules.TaskComplete(task.go:34)] Sync task 9653dc4a-9686-4277-8663-c56c2588f5ca complete succ
[error 2023-05-10 06:03:59 sysutils.GetSysConfig(kvm.go:207)] read /sys/class/net/em3/speed: invalid argument
[error 2023-05-10 06:03:59 sysutils.GetSysConfig(kvm.go:207)] read /sys/class/net/em3/carrier: invalid argument
[error 2023-05-10 06:03:59 sysutils.GetSysConfig(kvm.go:207)] read /sys/class/net/em4/speed: invalid argument
[error 2023-05-10 06:03:59 sysutils.GetSysConfig(kvm.go:207)] read /sys/class/net/em4/carrier: invalid argument
[error 2023-05-10 06:04:59 sysutils.GetSysConfig(kvm.go:207)] read /sys/class/net/em3/speed: invalid argument
[error 2023-05-10 06:04:59 sysutils.GetSysConfig(kvm.go:207)] read /sys/class/net/em3/carrier: invalid argument
[error 2023-05-10 06:04:59 sysutils.GetSysConfig(kvm.go:207)] read /sys/class/net/em4/speed: invalid argument
[error 2023-05-10 06:04:59 sysutils.GetSysConfig(kvm.go:207)] read /sys/class/net/em4/carrier: invalid argument
[info 2023-05-10 06:05:14 appsrv.(*Application).ServeHTTP(appsrv.go:278)] weBmhgZbz7NimkNwz9sQ3GC_HXs= 200 84edc3-9a25a9-9a3748 POST /servers/901f3c25-3ce8-47bd-8833-c287485fe6a4/sync (10.40.250.189:46544:compute_v2) 0.54ms
[error 2023-05-10 06:05:14 workmanager.(*workerTask).Run.func1(manager.go:71)] DelayTask panic: runtime error: invalid memory address or nil pointer dereference
goroutine 313117 [running]:
runtime/debug.Stack()
	/usr/lib/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/usr/lib/go/src/runtime/debug/stack.go:16 +0x19
yunion.io/x/onecloud/pkg/cloudcommon/workmanager.(*workerTask).Run.func1()
	/root/go/src/yunion.io/x/onecloud/pkg/cloudcommon/workmanager/manager.go:72 +0x85
panic({0x291bb80, 0x53bd610})
	/usr/lib/go/src/runtime/panic.go:838 +0x207
yunion.io/x/onecloud/pkg/hostman/guestman.(*SKVMGuestInstance).compareDescCdroms(0xc00199c7e0, 0xc001475500?)
	/root/go/src/yunion.io/x/onecloud/pkg/hostman/guestman/qemu-kvm.go:1872 +0x1f2
yunion.io/x/onecloud/pkg/hostman/guestman.(*SKVMGuestInstance).SyncConfig(0xc00199c7e0, {0x3499430?, 0xc001e77620}, 0xc001475500, 0x0)
	/root/go/src/yunion.io/x/onecloud/pkg/hostman/guestman/qemu-kvm.go:2045 +0x1ea
yunion.io/x/onecloud/pkg/hostman/guestman.(*SGuestManager).GuestSync(0x3497698?, {0x3499430, 0xc001e77620}, {0x2793f00?, 0xc0029236e0})
	/root/go/src/yunion.io/x/onecloud/pkg/hostman/guestman/guestman.go:878 +0x1b7
yunion.io/x/onecloud/pkg/cloudcommon/workmanager.(*workerTask).Run(0xc001e77650)
	/root/go/src/yunion.io/x/onecloud/pkg/cloudcommon/workmanager/manager.go:90 +0xce
yunion.io/x/onecloud/pkg/appsrv.execCallback(0xc0006a7f80?)
	/root/go/src/yunion.io/x/onecloud/pkg/appsrv/workers.go:249 +0x58
yunion.io/x/onecloud/pkg/appsrv.(*SWorker).run(0xc001e77680)
	/root/go/src/yunion.io/x/onecloud/pkg/appsrv/workers.go:92 +0x70
created by yunion.io/x/onecloud/pkg/appsrv.(*SWorkerManager).scheduleWithLock
	/root/go/src/yunion.io/x/onecloud/pkg/appsrv/workers.go:268 +0x165
[info 2023-05-10 06:05:14 modules.TaskComplete(task.go:34)] Sync task 2e5cceb8-cf88-4237-8f94-d09e9e7fdb6b complete succ
```

**Comment by wanyaoqi** [comment]
Hi @saltfishh  , 感谢反馈，这个问题已经修复过了，升级到最新版本的3.10.1可以解决

**Comment by saltfishh** [comment]
> Hi @saltfishh , 感谢反馈，这个问题已经修复过了，升级到最新版本的3.10.1可以解决

升级后正常, 感谢回复.
