### ISSUE TITLE
关于部分镜像无法使用的求助

### ISSUE THREAD

**Issue by saltfishh** [yunionio/cloudpods#17640]
### 内核及版本
- cloudpods: v3.10.1
- host: centos7.9_2009
- kernel:
  + master_node: 3.10.0-1160.6.1.el7.yn20201125.x86_64 
  + compute_node: Linux cloudpods-node4 5.4.130-1.yn20221208.el7.x86_64

### 问题描述
使用之前已经传过封装好的镜像及ISO 无法启动, 提示:
- 磁盘分配失败

> 宿主机的磁盘健康是正常的, 当前只有一个之前封装好的镜像可以创建虚拟机, 其他的镜像都不行.

#### web err log

```bash
{
    "__reason__": {
        "reason": {
            "__reason__": {
                "reason": {
                    "image_id": "99e0dcd1-0bd6-45cd-8943-c4cf95fdad16",
                    "reason": {
                        "__reason__": "AcquireImage: remoteFile.Fetch: download: Remote file fetch GET https://default-glance:30292/v1/images/99e0dcd1-0bd6-45cd-8943-c4cf95fdad16?format=iso&scope=system error 500",
                        "__stage__": "OnImageCacheComplete",
                        "__status__": "error"
                    }
                },
                "stage": "OnImageCacheComplete"
            },
            "__stage__": "OnIsoPrepareComplete",
            "__status__": "error",
            "__task_name__": "StorageCacheImageTask"
        },
        "stage": "OnIsoPrepareComplete"
    },
    "__stage__": "OnCdromPrepared",
    "__status__": "error",
    "__task_name__": "GuestInsertIsoTask"
}
```

#### pod log

```bash
[error 2023-07-27 02:09:19 httperrors.HTTPError(httperrors.go:110)] Send error get image: s3 client not init
goroutine 431847 [running]:
runtime/debug.Stack()
        /usr/lib/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        /usr/lib/go/src/runtime/debug/stack.go:16 +0x19
yunion.io/x/onecloud/pkg/httperrors.HTTPError({0x1588188?, 0xc001506690?}, {0x1586e80?, 0xc0015a21a0?}, {0xc000197f20, 0x1d}, 0x1f4, {0x137bb0f, 0x11}, {{0xc000197f20, ...}, ...})
        /root/go/src/yunion.io/x/onecloud/pkg/httperrors/httperrors.go:112 +0x405
yunion.io/x/onecloud/pkg/httperrors.JsonClientError(...)
        /root/go/src/yunion.io/x/onecloud/pkg/httperrors/httperrors.go:117
yunion.io/x/onecloud/pkg/appsrv/dispatcher.getHandler({0x1588188, 0xc001506690}, {0x1586e80, 0xc0015a21a0}, 0x12f8ec0?)
        /root/go/src/yunion.io/x/onecloud/pkg/appsrv/dispatcher/dispatcher.go:280 +0x21c
yunion.io/x/onecloud/pkg/mcclient/auth.AuthenticateWithDelayDecision.func1({0x1588188, 0xc001506660}, {0x1586e80, 0xc0015a21a0}, 0xc001502100)
        /root/go/src/yunion.io/x/onecloud/pkg/mcclient/auth/middleware.go:84 +0x33a
yunion.io/x/onecloud/pkg/appsrv.(*appTask).Run.func1(0xc0015a2160)
        /root/go/src/yunion.io/x/onecloud/pkg/appsrv/appsrv.go:332 +0x112
yunion.io/x/onecloud/pkg/appsrv.(*appTask).Run(0xc0015a2160)
        /root/go/src/yunion.io/x/onecloud/pkg/appsrv/appsrv.go:333 +0x365
yunion.io/x/onecloud/pkg/appsrv.execCallback(0xc000eeafb8?)
        /root/go/src/yunion.io/x/onecloud/pkg/appsrv/workers.go:249 +0x58
yunion.io/x/onecloud/pkg/appsrv.(*SWorker).run(0xc001506480)
        /root/go/src/yunion.io/x/onecloud/pkg/appsrv/workers.go:92 +0x70
created by yunion.io/x/onecloud/pkg/appsrv.(*SWorkerManager).scheduleWithLock
        /root/go/src/yunion.io/x/onecloud/pkg/appsrv/workers.go:268 +0x165
[info 2023-07-27 02:09:19 appsrv.(*Application).ServeHTTP(appsrv.go:278)] YGgu6BMFY3kqattg67DCEVrlc8c= 500 adc95c GET /v1/images/99e0dcd1-0bd6-45cd-8943-c4cf95fdad16?format=iso&scope=system (10.40.184.192:53696) 9.37ms
[info 2023-07-27 02:09:19 appsrv.(*Application).ServeHTTP(appsrv.go:278)] YGgu6BMFY3kqattg67DCEVrlc8c= 200 b3176f HEAD /v1/images/99e0dcd1-0bd6-45cd-8943-c4cf95fdad16?format=iso&scope=system (10.40.184.192:53698) 6.75ms
[error 2023-07-27 02:09:19 httperrors.HTTPError(httperrors.go:110)] Send error get image: s3 client not init
goroutine 431946 [running]:
runtime/debug.Stack()
        /usr/lib/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        /usr/lib/go/src/runtime/debug/stack.go:16 +0x19
yunion.io/x/onecloud/pkg/httperrors.HTTPError({0x1588188?, 0xc000422c90?}, {0x1586e80?, 0xc0015a2460?}, {0xc001395f00, 0x1d}, 0x1f4, {0x137bb0f, 0x11}, {{0xc001395f00, ...}, ...})
        /root/go/src/yunion.io/x/onecloud/pkg/httperrors/httperrors.go:112 +0x405
yunion.io/x/onecloud/pkg/httperrors.JsonClientError(...)
        /root/go/src/yunion.io/x/onecloud/pkg/httperrors/httperrors.go:117
yunion.io/x/onecloud/pkg/appsrv/dispatcher.getHandler({0x1588188, 0xc000422c90}, {0x1586e80, 0xc0015a2460}, 0x12f8ec0?)
        /root/go/src/yunion.io/x/onecloud/pkg/appsrv/dispatcher/dispatcher.go:280 +0x21c
yunion.io/x/onecloud/pkg/mcclient/auth.AuthenticateWithDelayDecision.func1({0x1588188, 0xc000422c60}, {0x1586e80, 0xc0015a2460}, 0xc000f5a200)
        /root/go/src/yunion.io/x/onecloud/pkg/mcclient/auth/middleware.go:84 +0x33a
yunion.io/x/onecloud/pkg/appsrv.(*appTask).Run.func1(0xc0015a2420)
        /root/go/src/yunion.io/x/onecloud/pkg/appsrv/appsrv.go:332 +0x112
yunion.io/x/onecloud/pkg/appsrv.(*appTask).Run(0xc0015a2420)
        /root/go/src/yunion.io/x/onecloud/pkg/appsrv/appsrv.go:333 +0x365
yunion.io/x/onecloud/pkg/appsrv.execCallback(0xc001800fb8?)
        /root/go/src/yunion.io/x/onecloud/pkg/appsrv/workers.go:249 +0x58
yunion.io/x/onecloud/pkg/appsrv.(*SWorker).run(0xc000422a80)
        /root/go/src/yunion.io/x/onecloud/pkg/appsrv/workers.go:92 +0x70
created by yunion.io/x/onecloud/pkg/appsrv.(*SWorkerManager).scheduleWithLock
        /root/go/src/yunion.io/x/onecloud/pkg/appsrv/workers.go:268 +0x165
[info 2023-07-27 02:09:19 appsrv.(*Application).ServeHTTP(appsrv.go:278)] YGgu6BMFY3kqattg67DCEVrlc8c= 500 273db2 GET /v1/images/99e0dcd1-0bd6-45cd-8943-c4cf95fdad16?format=iso&scope=system (10.40.184.192:53702) 6.83ms
```

**Comment by saltfishh** [comment]
新上传了一个ISO镜像, 使用该镜像创建虚拟机.
状态一直为 `分配磁盘`
glance pod log:

```bash
kubectl logs -n onecloud --tail 200 default-glance-fd69959f7-wdr5b | grep cycle


[warning 2023-07-27 02:42:11 appsrv.do_worker_watchdog(workers_watchdog.go:64)] WorkerManager image_streaming_worker has been busy for 2 cycles...
[warning 2023-07-27 02:42:41 appsrv.do_worker_watchdog(workers_watchdog.go:64)] WorkerManager image_streaming_worker has been busy for 3 cycles...
[warning 2023-07-27 02:43:11 appsrv.do_worker_watchdog(workers_watchdog.go:64)] WorkerManager image_streaming_worker has been busy for 4 cycles...
[warning 2023-07-27 02:43:41 appsrv.do_worker_watchdog(workers_watchdog.go:64)] WorkerManager image_streaming_worker has been busy for 5 cycles...
[warning 2023-07-27 02:44:11 appsrv.do_worker_watchdog(workers_watchdog.go:64)] WorkerManager image_streaming_worker has been busy for 6 cycles...
[warning 2023-07-27 02:44:41 appsrv.do_worker_watchdog(workers_watchdog.go:64)] WorkerManager image_streaming_worker has been busy for 7 cycles...
[warning 2023-07-27 02:45:11 appsrv.do_worker_watchdog(workers_watchdog.go:64)] WorkerManager image_streaming_worker has been busy for 8 cycles...
[warning 2023-07-27 02:45:41 appsrv.do_worker_watchdog(workers_watchdog.go:64)] WorkerManager image_streaming_worker has been busy for 9 cycles...
[warning 2023-07-27 02:46:11 appsrv.do_worker_watchdog(workers_watchdog.go:64)] WorkerManager image_streaming_worker has been busy for 10 cycles...
[warning 2023-07-27 02:46:41 appsrv.do_worker_watchdog(workers_watchdog.go:64)] WorkerManager image_streaming_worker has been busy for 11 cycles...
[warning 2023-07-27 02:47:11 appsrv.do_worker_watchdog(workers_watchdog.go:64)] WorkerManager image_streaming_worker has been busy for 12 cycles...
[warning 2023-07-27 02:47:41 appsrv.do_worker_watchdog(workers_watchdog.go:64)] WorkerManager image_streaming_worker has been busy for 13 cycles...
[warning 2023-07-27 02:48:11 appsrv.do_worker_watchdog(workers_watchdog.go:64)] WorkerManager image_streaming_worker has been busy for 14 cycles...
[warning 2023-07-27 02:48:41 appsrv.do_worker_watchdog(workers_watchdog.go:64)] WorkerManager image_streaming_worker has been busy for 15 cycles...
[warning 2023-07-27 02:49:11 appsrv.do_worker_watchdog(workers_watchdog.go:64)] WorkerManager image_streaming_worker has been busy for 16 cycles...
[warning 2023-07-27 02:49:41 appsrv.do_worker_watchdog(workers_watchdog.go:64)] WorkerManager image_streaming_worker has been busy for 17 cycles...
[warning 2023-07-27 02:50:11 appsrv.do_worker_watchdog(workers_watchdog.go:64)] WorkerManager image_streaming_worker has been busy for 18 cycles...
[warning 2023-07-27 02:50:41 appsrv.do_worker_watchdog(workers_watchdog.go:64)] WorkerManager image_streaming_worker has been busy for 19 cycles...
```

**Comment by zexi** [comment]
@saltfishh 看起来是你的环境的 glance 服务初始化连接 minio s3 接口失败了，麻烦执行下面的命令把配置信息发出来下：

```bash
kubectl get configmap -n onecloud default-glance

climc service-config-show glance
```

**Comment by saltfishh** [comment]
@zexi 

```bash
[root@cloud-stack ~]# kubectl get configmap -n onecloud default-glance
NAME             DATA   AGE
default-glance   1      142d
```

```bash
[root@cloud-stack ~]# climc service-config-show glance
{
  "config":
    {
      "default":
        {
          "auth_token_cache_size": 2048,
          "calculate_quota_usage_interval_seconds": 900,
          "cron_job_worker_count": 4,
          "debug_client": false,
          "default_image_quota": 10,
          "enable_pending_delete": true,
          "enable_torrent_service": false,
          "filesystem_store_datadir": "/opt/cloud/workspace/data/glance/images",
          "historical_unique_name": false,
          "log_timestamp_format": "2006-01-02 15:04:05",
          "log_with_time_zone": "UTC",
          "pending_delete_check_seconds": 3600,
          "pending_delete_expire_seconds": 259200,
          "pending_delete_max_clean_batch_size": 50,
          "policy_worker_count": 1,
          "query_offset_optimization": false,
          "rbac_debug": false,
          "rbac_policy_refresh_interval_seconds": 30,
          "request_worker_count": 8,
          "s3_access_key": "minioadmin",
          "s3_bucket_name": "onecloud-images",
          "s3_check_image_status": false,
          "s3_endpoint": "minio.onecloud-minio:9000",
          "s3_mount_point": "/opt/cloud/workspace/data/glance/s3images",
          "s3_secret_key": "yunionminio@admin",
          "s3_use_ssl": false,
          "storage_driver": "local",
          "target_image_formats":
            [
              "qcow2",
              "vmdk"
            ],
          "task_worker_count": 4,
          "tenant_cache_expire_seconds": 900,
          "torrent_client_path": "/opt/yunion/bin/torrent",
          "torrent_store_dir": "/opt/cloud/workspace/data/glance/torrents"
        }
    }
}
[root@cloud-stack ~]#
```

**Comment by saltfishh** [comment]
将原镜像删除后, 重新上传镜像, 就可以正常安装了. 很奇怪.
之前的镜像挂载到虚拟机上, 显示挂载成功, 但是虚拟机内部是看不到的.

**Comment by zexi** [comment]
@saltfishh 看起来配置里面使用的是 local 的本地目录来保存镜像，应该不存在这个连接 s3 对象存储的问题，可以把 default-glance 这个 deployment 的 image 升级到 v3.10.3 后再试试，升级的命令为：
```bash
kubectl set image -n onecloud deploy/default-glance *=registry.cn-beijing.aliyuncs.com/yunionio/glance:v3.10.3
```

**Comment by saltfishh** [comment]
@zexi 感谢帮助.
