### ISSUE TITLE
[求助/Help]3.10.5高可用集群一直提示initHostRecord: master ip not found

### ISSUE THREAD

**Issue by SlyChen** [yunionio/cloudpods#18018]
问题：高可用集群部署完成后，WEB控制台页面可以正常打开。default-host-xxx一直提示`register failed: initHostRecords: initHostRecord: master ip `，通过`climc host-list`无法发现宿主机。

集群及相关日志信息如下：
1. kubectl get pods
`# kubectl -n onecloud get pods  | egrep 'default-host.*.3|telegraf' 
default-host-jt2rh                                   3/3     Running                 0          44m
default-host-p27g7                                   3/3     Running                 0          44m
default-host-vxf5r                                   3/3     Running                 0          44m
default-telegraf-549fl                               0/1     Init:CrashLoopBackOff   4          2m10s
default-telegraf-7d2bx                               0/1     Init:CrashLoopBackOff   4          2m8s
default-telegraf-8s5zk                               0/1     Init:CrashLoopBackOff   4          2m2s`

2. default-host-xxx 日志
`[error 2023-09-14 07:24:35 hostinfo.(*SHostInfo).onFail(hostinfo.go:1115)] register failed: initHostRecords: initHostRecord: master ip not found
[error 2023-09-14 07:24:35 timeutils2.AddTimeout.func1.1(timeutils.go:31)] register failed, try 30 seconds later...
goroutine 904 [running]:
runtime/debug.Stack()
	/usr/lib/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/usr/lib/go/src/runtime/debug/stack.go:16 +0x19
yunion.io/x/onecloud/pkg/util/timeutils2.AddTimeout.func1.1()
	/root/go/src/yunion.io/x/onecloud/pkg/util/timeutils2/timeutils.go:32 +0x59
panic({0x284ec00, 0x34ca600})
	/usr/lib/go/src/runtime/panic.go:838 +0x207
yunion.io/x/onecloud/pkg/hostman/hostinfo.(*SHostInfo).onFail(0xc000a8c180, {0x2b36b20?, 0xc0001ee090?})
	/root/go/src/yunion.io/x/onecloud/pkg/hostman/hostinfo/hostinfo.go:1117 +0xeb
yunion.io/x/onecloud/pkg/hostman/hostinfo.(*SHostInfo).register(0xc000a8c180)
	/root/go/src/yunion.io/x/onecloud/pkg/hostman/hostinfo/hostinfo.go:1082 +0x6f
yunion.io/x/onecloud/pkg/util/timeutils2.AddTimeout.func1()
	/root/go/src/yunion.io/x/onecloud/pkg/util/timeutils2/timeutils.go:37 +0x5c
created by yunion.io/x/onecloud/pkg/util/timeutils2.AddTimeout
	/root/go/src/yunion.io/x/onecloud/pkg/util/timeutils2/timeutils.go:28 +0x65
`

3. 另外telegraf挂载的配置目录没有数据，附带提下。
`# kubectl -n onecloud logs default-telegraf-549fl telegraf
Error from server (BadRequest): container "telegraf" in pod "default-telegraf-549fl" is waiting to start: PodInitializing
# ls -al /etc/telegraf/
total 12
drwxr-xr-x   2 root root    6 Sep 14 15:20 .
drwxr-xr-x. 97 root root 8192 Sep 13 14:40 ..`

4. 无法发现宿主机
`# climc host-list
***  Total: 0  ***`

5. /etc/yunion/host.conf的网络配置
`networks:
- team0/br0/bcast0`

IP信息说明：
10.16.40.10：管理IP，配置在team0.1001上。
10.16.40.18:  cloudpods集群的VIP。
10.16.40.19:  数据库的VIP。
10.16.42.10：CEPH网络的IP，走另一个bond。
`    inet 10.16.40.10/24 brd 10.16.40.255 scope global team0.1001
    inet 10.16.40.18/32 scope global team0.1001
    inet 10.16.40.19/32 scope global team0.1001
    inet 10.16.42.10/24 brd 10.16.42.255 scope global team1.1003`

6. ovs-vsctl show
`    Bridge "br0"
        Port "team0"
            Interface "team0"
        Port "br0"
            Interface "br0"
                type: internal
`

**Comment by wanyaoqi** [comment]
@SlyChen  team0 没有分配 ip 吗

**Comment by SlyChen** [comment]
> @SlyChen team0 没有分配 ip 吗

team0是没有分配IP的，交换机端口配置的trunk，所以管理IP配置在带vlan标记的team0.1001上。cloudpods初始化时，br0自动配置了169.254.x.x

**Comment by wanyaoqi** [comment]
@SlyChen 需要一个有ip的网卡作为宿主机和控制节点通信，比如 eth0
在 /etc/yunion/host.conf 中加一个配置
```
$ vi /etc/yunion/host.conf
listen_interface: eth0
```

**Comment by zexi** [comment]
@SlyChen 配置完 /etc/yunion/host.conf 后，需要删除下 default-host-xxx 相关的 pod ，等这些 pod 重建下才能读取配置

**Comment by SlyChen** [comment]
> @SlyChen 需要一个有ip的网卡作为宿主机和控制节点通信，比如 eth0 在 /etc/yunion/host.conf 中加一个配置
> 
> ```
> $ vi /etc/yunion/host.conf
> listen_interface: eth0
> ```
宿主机不是通过别名卡通信的吗？如图中的eth0.100，也就对应team0.1001。
![image](https://github.com/yunionio/cloudpods/assets/46590985/0b816b00-3746-45f0-872f-1a08bf5e8fc4)

**Comment by SlyChen** [comment]
> @SlyChen 配置完 /etc/yunion/host.conf 后，需要删除下 default-host-xxx 相关的 pod ，等这些 pod 重建下才能读取配置

了解，感谢提醒！
