### ISSUE TITLE
[求助/Help] 物理机--安装操作系统--新建失败

### ISSUE THREAD

**Issue by ChaoHsin-fang** [yunionio/cloudpods#18925]
![image](https://github.com/yunionio/cloudpods/assets/48585560/bcbed52d-dc0c-4235-9a61-fd71f150fac3)

日志：
{"log":"[info 2023-12-07 09:04:59 appsrv.(*Application).ServeHTTP(appsrv.go:288)] nZ-mH6QkpHzCj-dG0qtSHTbh9G4= 200 4a25a4 GET /api/v2/networks?scope=system\u0026show_fail_reason=true\u0026details=false\u0026limit=20 (10.111.230.2:55030) 5.40ms\n","stream":"stderr","time":"2023-12-07T09:04:59.169069392Z"}
{"log":"[info 2023-12-07 09:04:59 appsrv.(*Application).ServeHTTP(appsrv.go:288)] nZ-mH6QkpHzCj-dG0qtSHTbh9G4= 200 27a663 GET /api/v2/networks?scope=system\u0026show_fail_reason=true\u0026details=true\u0026limit=20 (10.111.230.2:55034) 16.63ms\n","stream":"stderr","time":"2023-12-07T09:04:59.275098475Z"}
{"log":"[info 2023-12-07 09:05:01 appsrv.(*Application).ServeHTTP(appsrv.go:288)] nZ-mH6QkpHzCj-dG0qtSHTbh9G4= 200 ee5288 GET /api/v2/networks/statistics?scope=system\u0026show_fail_reason=true\u0026details=true\u0026limit=20 (10.111.230.2:55060) 3.26ms\n","stream":"stderr","time":"2023-12-07T09:05:01.269528191Z"}
{"log":"[info 2023-12-07 09:05:08 appsrv.(*Application).ServeHTTP(appsrv.go:288)] nZ-mH6QkpHzCj-dG0qtSHTbh9G4= 200 0ace3d GET /api/v2/networks?limit=20\u0026vpc=default\u0026zone=2d80c45f-2110-48be-8fb7-54660d2edd5e\u0026usable=true\u0026filter=wire_id.in%287ee1841f-4d65-4f89-8bbf-df859087fa88%29\u0026scope=system\u0026host=1efc1a97-5ee7-4044-8750-4f6d87445401 (10.111.230.2:55244) 23.82ms\n","stream":"stderr","time":"2023-12-07T09:05:08.634718044Z"}
{"log":"[error 2023-12-07 09:05:21 httperrors.HTTPError(httperrors.go:110)] Send error 服务器内部错误：runtime error: index out of range [0] with length 0\n","stream":"stderr","time":"2023-12-07T09:05:21.854497117Z"}
{"log":"goroutine 390795 [running]:\n","stream":"stderr","time":"2023-12-07T09:05:21.854740604Z"}

**Comment by zexi** [comment]
@ChaoHsin-fang 麻烦把 region 服务的日志导出来，放到这里看下，需要知道是哪个地方 panic 了，另外说下你的 region 服务版本是多少？

**Comment by ChaoHsin-fang** [comment]
1.目前上面的报错已经过去了，原因可能是手残漏选了安装的磁盘，选上安装的磁盘，就过去这一步了。
但是web界面弹出的报错 服务器内部错误：runtime error: index out of range [0] with length 0 索引越界，
给人云里雾里的感觉，应该提示没有选择系统安装盘，比较准确，大概的分析也可能不准确，详细看下面的日志。
2.region版本 ：All in One 的方式部署私有云版本3.10

3.日志：
[1.log](https://github.com/yunionio/cloudpods/files/13608391/1.log)

**Comment by zexi** [comment]
@ChaoHsin-fang 这个日志不全，没有相关错误的日志。应该是被冲掉了，可以先在 web 前端复现下错误，然后再把 region 日志导出来，导出来可以搜下里面有没有 panic 或者 runtime 的关键字，有的话就能看到错误的堆栈信息了。

**Comment by ChaoHsin-fang** [comment]
@zexi 
![image](https://github.com/yunionio/cloudpods/assets/48585560/f6a82cbe-e341-46c1-939a-9d1917a1a06a)
有个问题比较疑惑， 我新建的是裸金属，装机的镜像是ISO 挂载，为啥资源类型这里展示的是虚拟机呢，我理解应该是裸金属

**Comment by zexi** [comment]
@ChaoHsin-fang 这里应该是前端翻译的问题，后端是这样抽象的裸金属资源，会把装完系统的物理机叫作“裸金属”，这个记录也是记录到虚拟机的数据库表里面的，里面有个 hypervisor 字段会把裸金属记录成 "baremetal"。

**Comment by ChaoHsin-fang** [comment]
[1.log](https://github.com/yunionio/cloudpods/files/13613240/1.log)

**Comment by zexi** [comment]
> 我这边复现了这个问题 安装系统--不选磁盘。
> 
> 界面会报错：
> 
> 错误消息: InternalServerError 服务器内部错误：runtime error: index out of range [0] with length 0 错误源信息: { "class": "InternalServerError", "code": 500, "details": "服务器内部错误：runtime error: index out of range [0] with length 0", "time": "2023-12-08T19:01:16+08:00" }
> 
> { "method": "post", "url": "/v2/servers", "headers": { "Accept": "application/json, text/plain, _/_", "Content-Type": "application/json;charset=utf-8", "x-yunion-lang": "zh-CN" }, "data": { "project_id": "bb7dc551694e467b8c1d5a4959cc7f8e", "count": 1, "vmem_size": 524288, "vcpu_count": 96, "generate_name": "bms-131", "hypervisor": "baremetal", "auto_start": true, "vdi": "vnc", "disks": [], "baremetal_disk_configs": [], "nets": [ { "network": "ad5f3f8b-9675-4c37-8da9-95215648d1e7" } ], "prefer_host": "c5bf75a4-3abe-4f39-880c-2632a0508187", "prefer_region": "default", "prefer_zone": "2d80c45f-2110-48be-8fb7-54660d2edd5e", "cdrom": "900938f2-8473-4a62-81ef-e5e68480fd24" } }
> 
> 我理解提示：未选择磁盘，请选择安装系统盘，友好些
> 
> region日志：

@ChaoHsin-fang 感谢反馈这个问题，我们修改下。/keep-state
