### ISSUE TITLE
[求助/Help]VPC二层网络的疑惑

### ISSUE THREAD

**Issue by zhfish** [yunionio/cloudpods#19608]
服务器由千兆端口部署了私有云，然后希望有万兆端口进行虚拟机之间的数据通信和EIP
目前EIP可以指定二层网络，但VPC自动建立了ovn的虚拟二层网络
请问vpc的二层网络如何指定到bond0(wire20g)？
```
# cat /etc/yunion/host.conf | grep networks -A 5 -B5                                                                                                       [11:31:31] 
- /opt/cloud/workspace/disks
log_level: info
log_verbose_level: 0
manage_ntp_configuration: true
max_reserved_memory: 10240
networks:
- enp44s0f0/br0/10.106.1.32
- bond0/br1/wire20g
non_default_domain_projects: false
notify_admin_users:
- sysadmin
```
![image](https://github.com/yunionio/cloudpods/assets/287033/50892f7c-208b-4ed6-8229-51d80cd1d079)

**Comment by swordqiu** [comment]
@zhfish 请参考文档：https://www.cloudpods.org/docs/guides/onpremise/network/examples/#%E5%8F%8C%E7%BD%91%E5%8F%A3vpc%E7%BD%91%E7%BB%9C-%E8%AE%A1%E7%AE%97%E8%8A%82%E7%82%B9%E4%B8%A4%E4%B8%AA%E7%BD%91%E5%8F%A3%E8%99%9A%E6%8B%9F%E6%9C%BA%E4%BD%BF%E7%94%A8vpc%E7%BD%91%E7%BB%9C

需要在20G网口配置IP，并配置 ovn_encap_ip，确保vpc流量使用20G的网口

**Comment by zhfish** [comment]
谢谢，我把这个内容和eip的二层网络搞混了

**Comment by zhfish** [comment]
20G网口配置IP，这里在bond0上建立了带vlan的interface
形成了如下配置
```
# cat /etc/yunion/host.conf | grep networks -A 5 -B5                                                                                                       [11:31:31] 
log_level: info
log_verbose_level: 0
manage_ntp_configuration: true
max_reserved_memory: 10240
ovn_encap_ip: 10.106.5.32
networks:
- enp44s0f0/br0/10.106.1.32
- bond0/br1/wire20g
- vnet/br2/10.106.5.32
non_default_domain_projects: false
```
重启host会失败,
```
[info 2024-03-04 07:20:20 hostinfo.(*SHostInfo).ensureMasterNetworks(hostinfo.go:1208)] Master ip 10.106.7.32 to fetch wire
[info 2024-03-04 07:20:20 hostinfo.(*SHostInfo).tryCreateNetworkOnWire(hostinfo.go:1179)] Get master ip 10.106.5.32 and mask 24
[error 2024-03-04 07:20:20 hostinfo.(*SHostInfo).onFail(hostinfo.go:1105)] register failed: initHostRecords: initHostRecord: try create network: find_matched == false: InvalidStatusError
panic: exit immediately for retry...

goroutine 1 [running]:
yunion.io/x/onecloud/pkg/hostman/hostinfo.(*SHostInfo).onFail(0xc000e29080, {0x3624940?, 0xc0015093b0?})
        /root/go/src/yunion.io/x/onecloud/pkg/hostman/hostinfo/hostinfo.go:1108 +0x44a
yunion.io/x/onecloud/pkg/hostman/hostinfo.(*SHostInfo).register(0xc000e29080)
        /root/go/src/yunion.io/x/onecloud/pkg/hostman/hostinfo/hostinfo.go:1072 +0x6d
yunion.io/x/onecloud/pkg/hostman/hostinfo.(*SHostInfo).StartRegister(0xc0001ea4d0?, 0xc0002d4f00?)
        /root/go/src/yunion.io/x/onecloud/pkg/hostman/hostinfo/hostinfo.go:1049 +0x32
yunion.io/x/onecloud/pkg/hostman.(*SHostService).RunService(0xc000e2c040?)
        /root/go/src/yunion.io/x/onecloud/pkg/hostman/host_services.go:107 +0x308
yunion.io/x/onecloud/pkg/cloudcommon/service.(*SServiceBase).StartService(0xc000c80cf0)
        /root/go/src/yunion.io/x/onecloud/pkg/cloudcommon/service/services.go:58 +0xfa
yunion.io/x/onecloud/pkg/hostman.StartService(...)
        /root/go/src/yunion.io/x/onecloud/pkg/hostman/host_services.go:163
ignore_nonrunning_guests: true
main.main()
        /root/go/src/yunion.io/x/onecloud/cmd/host/main.go:30 +0x10a
```

是因为vlan子接口不能被桥接么？
那带vlan的ip应该如何配置？

**Comment by swordqiu** [comment]
@zhfish 
这个报错：
register failed: initHostRecords: initHostRecord: try create network: find_matched == false: InvalidStatusError
是说平台没有10.106.1.32或10.106.5.32对应的IP子网
加上对应IP子网就可以了。需要注意IP子网注册在不同的wire上（因为是在不同的网口）

**Comment by zhfish** [comment]
> @zhfish 这个报错： register failed: initHostRecords: initHostRecord: try create network: find_matched == false: InvalidStatusError 是说平台没有10.106.1.32或10.106.5.32对应的IP子网 加上对应IP子网就可以了。需要注意IP子网注册在不同的wire上（因为是在不同的网口）

我自己加了IP子网，会出现别的错误，后来我把cloudpod都卸载了，把千兆网卡关上，只留了一个bond0(聚合)和vnet(带vlan和ip)   
重新安装后host报错

```
[info 2024-03-13 06:19:39 hostinfo.(*SHostInfo).doUploadNicInfoInternal(hostinfo.go:1747)] Upload NIC br:br0 if:vnet
[error 2024-03-13 06:19:39 hostinfo.(*SHostInfo).onFail(hostinfo.go:1105)] register failed: initHostNetworks: uploadNetworkInfo: doSyncNicInfo vnet: doUploadNicInfoInternal: modules.Hosts.PerformAction add-netif: {"error":{"class":"BadRequestError","code":400,"details":"addNetif: {\"error\":{\"class\":\"BadRequestError\",\"code\":400,\"data\":{\"fields\":[{}],\"id\":\"%!v(MISSING)\"},\"details\":\"hh.Attach2Network: net.GetFreeIP: getFreeIP: {\\\"error\\\":{\\\"class\\\":\\\"InsufficientResourceError\\\",\\\"code\\\":400,\\\"data\\\":{\\\"id\\\":\\\"Out of IP address\\\"},\\\"details\\\":\\\"Out of IP address\\\"}}\"}}","request":{"body":"{\"host\":{\"bridge\":\"br0\",\"interface\":\"vnet\",\"ip_addr\":\"10.106.5.32\",\"link_up\":true,\"mac\":\"08:c0:eb:1...id\":875,\"wire\":\"bcast0\"}}","headers":{"Content-Length":"174","Content-Type":"application/json","User-Agent":"yunioncloud-go/201708","X-Auth-Token":"*","X-Yunion-Parent-Id":"","X-Yunion-Peer-Service-Name":"host","X-Yunion-Remote-Addr":"default-region:30888","X-Yunion-Span-Id":"0","X-Yunion-Span-Name":"","X-Yunion-Strace-Debug":"true","X-Yunion-Strace-Id":"98fcdf2e"},"method":"POST","url":"https://default-region:30888/hosts/d3bfe07e-18d6-4e76-8bca-4d0f38cd1bc4/add-netif"}}}
[error 2024-03-13 06:19:39 notifyclient.(*eventTask).Run(notify.go:299)] unable to EventNotify: {"error":{"class":"NotFoundError","code":404,"details":"unable fetch subscriptions by event \"HOST/EXCEPTION/SUCCEED\": eventStr:HOST/EXCEPTION/SUCCEED: NotFoundError","request":{"body":"{\"notifications\":{\"advance_days\":0,\"event\":\"HOST/EXCEPTION/SUCCEED\",\"priority\":\"fatal\",\"resource_det...f\\\"}}}\",\"name\":\"gpu33\"}}}","headers":{"Content-Length":"1544","Content-Type":"application/json","User-Agent":"yunioncloud-go/201708","X-Auth-Token":"*","X-Yunion-Parent-Id":"","X-Yunion-Peer-Service-Name":"host","X-Yunion-Remote-Addr":"default-notify:30777","X-Yunion-Span-Id":"0","X-Yunion-Span-Name":"","X-Yunion-Strace-Debug":"true","X-Yunion-Strace-Id":"f69124f0"},"method":"POST","url":"https://default-notify:30777/v2/notifications/event-notify"}}}
panic: exit immediately for retry...

goroutine 1 [running]:
yunion.io/x/onecloud/pkg/hostman/hostinfo.(*SHostInfo).onFail(0xc000cce9a0, {0x3624940?, 0xc001ed18d8?})
        /root/go/src/yunion.io/x/onecloud/pkg/hostman/hostinfo/hostinfo.go:1108 +0x44a
yunion.io/x/onecloud/pkg/hostman/hostinfo.(*SHostInfo).register(0xc000cce9a0)
        /root/go/src/yunion.io/x/onecloud/pkg/hostman/hostinfo/hostinfo.go:1082 +0xfb
yunion.io/x/onecloud/pkg/hostman/hostinfo.(*SHostInfo).StartRegister(0xc0007fb550?, 0xc00044a900?)
        /root/go/src/yunion.io/x/onecloud/pkg/hostman/hostinfo/hostinfo.go:1049 +0x32
yunion.io/x/onecloud/pkg/hostman.(*SHostService).RunService(0xc0002363c0?)
        /root/go/src/yunion.io/x/onecloud/pkg/hostman/host_services.go:107 +0x308
yunion.io/x/onecloud/pkg/cloudcommon/service.(*SServiceBase).StartService(0xc0002323f0)
        /root/go/src/yunion.io/x/onecloud/pkg/cloudcommon/service/services.go:58 +0xfa
yunion.io/x/onecloud/pkg/hostman.StartService(...)
        /root/go/src/yunion.io/x/onecloud/pkg/hostman/host_services.go:163
main.main()
        /root/go/src/yunion.io/x/onecloud/cmd/host/main.go:30 +0x10a
```

**Comment by hoganlxj** [comment]
> Out of IP address

看着是IP子网没有可用的ip，  10.106.5.32 这个在cloudpods被分配没？

**Comment by zhfish** [comment]
这个关闭了，我基于全新的环境，重新开一个issue
