### ISSUE TITLE
[求助/Help] telegraf.conf 配置文件未自动生成，宿主机始终在初始化 

### ISSUE THREAD

**Issue by weiwhy** [yunionio/cloudpods#19914]
我遇到和[https://github.com/yunionio/cloudpods/issues/18745](https://github.com/yunionio/cloudpods/issues/18745)这个issue相同的问题，环境为ubutnu2204，我觉得应该不是显卡的问题，
host POD的日志内容如下：
```
[info 2024-04-09 08:37:24 isolated_device.getPassthroughGPUS(gpu.go:66)] filter address []
[info 2024-04-09 08:37:24 isolated_device.(*PCIDevice).IsBootVGA(gpu.go:368)] PCI address 02:00.0 is boot_vga: /sys/devices/pci0000:00/0000:00:1c.0/0000:01:00.0/0000:02:00.0/boot_vga
[info 2024-04-09 08:37:24 isolated_device.(*PCIDevice).forceBindVFIOPCIDriver(gpu.go:386)] &isolated_device.PCIDevice{Addr:"02:00.0", ClassName:"VGA compatible controller", ClassCode:"0300", VendorName:"ASPEED Technology, Inc.", VendorId:"1a03", DeviceName:"ASPEED Graphics Family", DeviceId:"2000", SubvendorName:"ASPEED Technology, Inc.", SubvendorId:"1a03", SubdeviceName:"ASPEED Graphics Family", SubdeviceId:"2000", ModelName:"", RestIOMMUGroupDevs:[]*isolated_device.PCIDevice(nil)}is boot vga card, skip it
[warning 2024-04-09 08:37:25 isolated_device.getPassthroughGPUS(gpu.go:90)] GPU {"bus_id":"02:00.0","class_code":"0300","class_name":"VGA compatible controller","device_id":"2000","device_name":"ASPEED Graphics Family","subdevice_id":"2000","subdevice_name":"ASPEED Graphics Family","subvendor_id":"1a03","subvendor_name":"ASPEED Technology, Inc.","vendor_id":"1a03","vendor_name":"ASPEED Technology, Inc."} use kernel driver "ast", skip it
[info 2024-04-09 08:37:25 storageman.(*SLocalStorage).GetAvailSizeMb(storage_local.go:209)] Storage /opt/cloud/workspace/disks and kubelet imageFs /opt/docker share same device /dev/mapper/vg0-lv--0
[info 2024-04-09 08:37:25 storageman.(*SLocalStorage).GetAvailSizeMb(storage_local.go:221)] Storage /opt/cloud/workspace/disks sizeMb 21746087, usablePercent 0.950000
[info 2024-04-09 08:37:25 storageman.(*SLocalStorage).SyncStorageInfo(storage_local.go:255)] Sync storage info /host_10.7.8.35_local_storage_0
[info 2024-04-09 08:37:25 hostinfo.(*SHostInfo).onSyncStorageInfoSucc(hostinfo.go:1878)] storage id
[error 2024-04-09 08:37:25 hostinfo.(*SHostInfo).onSyncStorageInfoSucc(hostinfo.go:1880)] storage config %!s(<nil>)
[error 2024-04-09 08:37:25 timeutils2.AddTimeout.func1.1(timeutils.go:31)] runtime error: invalid memory address or nil pointer dereference
goroutine 732 [running]:
runtime/debug.Stack()
        /usr/lib/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        /usr/lib/go/src/runtime/debug/stack.go:16 +0x19
yunion.io/x/onecloud/pkg/util/timeutils2.AddTimeout.func1.1()
        /root/go/src/yunion.io/x/onecloud/pkg/util/timeutils2/timeutils.go:32 +0x59
panic({0x2955860, 0x542b8f0})
        /usr/lib/go/src/runtime/panic.go:838 +0x207
yunion.io/x/onecloud/pkg/hostman/hostinfo.(*SHostInfo).onSyncStorageInfoSucc(0xc001211700?, {0x3515078, 0xc001211700}, {0x0, 0x0})
        /root/go/src/yunion.io/x/onecloud/pkg/hostman/hostinfo/hostinfo.go:1881 +0x15f
yunion.io/x/onecloud/pkg/hostman/hostinfo.(*SHostInfo).initStoragesInternal(0xc0001ff800, {0x59deb68?, 0x0?, 0x0?})
        /root/go/src/yunion.io/x/onecloud/pkg/hostman/hostinfo/hostinfo.go:1868 +0x514
yunion.io/x/onecloud/pkg/hostman/hostinfo.(*SHostInfo).initStorages(0xc0001ff800?)
        /root/go/src/yunion.io/x/onecloud/pkg/hostman/hostinfo/hostinfo.go:1736 +0x6d
yunion.io/x/onecloud/pkg/hostman/hostinfo.(*SHostInfo).register(0xc0001ff800)
        /root/go/src/yunion.io/x/onecloud/pkg/hostman/hostinfo/hostinfo.go:1098 +0x14f
yunion.io/x/onecloud/pkg/util/timeutils2.AddTimeout.func1()
        /root/go/src/yunion.io/x/onecloud/pkg/util/timeutils2/timeutils.go:37 +0x5c
created by yunion.io/x/onecloud/pkg/util/timeutils2.AddTimeout
        /root/go/src/yunion.io/x/onecloud/pkg/util/timeutils2/timeutils.go:28 +0x65
```
感觉像是存储的问题，但是现在我不知道怎么开始着手排查问题

**Comment by weiwhy** [comment]
![image](https://github.com/yunionio/cloudpods/assets/25366558/34ed5669-fc75-4132-a1c3-4d104e8b0c12)

**Comment by weiwhy** [comment]
我感觉应该有一些兼容性的问题，
![image](https://github.com/yunionio/cloudpods/assets/25366558/ae740dda-95bb-41c5-92d2-9963e96b1085)
卷组是不是不好兼容

**Comment by weiwhy** [comment]
我现在正在使用的host镜像版本为registry.cn-beijing.aliyuncs.com/yunion/host:v3.10.5

**Comment by weiwhy** [comment]
我把host镜像的版本升级到registry.cn-beijing.aliyuncs.com/yunion/host:v3.10.7后问题解决了，没事儿了

**Comment by weiwhy** [comment]
![image](https://github.com/yunionio/cloudpods/assets/25366558/e4152e36-403c-4824-ac6e-e383f0885066)
前端没有正确识别挂载在opt的lvm的容量

**Comment by weiwhy** [comment]
![image](https://github.com/yunionio/cloudpods/assets/25366558/fba5a7ad-0535-46dc-bfc0-d8bd41d72ba8)
host的版本我切换到了registry.cn-beijing.aliyuncs.com/yunion/host:v3.10.12，还是没有办法正确识别这个容量

**Comment by weiwhy** [comment]
在3.10.12版本的日志里报错的内容如下：
```
[warning 2024-04-09 09:25:39 isolated_device.getPassthroughGPUS(gpu.go:102)] GPU {"bus_id":"02:00.0","class_code":"0300","class_name":"VGA compatible controller","device_id":"2000","device_name":"ASPEED Graphics Family","subdevice_id":"2000","subdevice_name":"ASPEED Graphics Family","subvendor_id":"1a03","subvendor_name":"ASPEED Technology, Inc.","vendor_id":"1a03","vendor_name":"ASPEED Technology, Inc."} use kernel driver "ast", skip it
[info 2024-04-09 09:25:39 storageman.(*SLocalStorage).GetAvailSizeMb(storage_local.go:209)] Storage /opt/cloud/workspace/disks and kubelet imageFs /opt/docker share same device /dev/mapper/vg0-lv--0
[info 2024-04-09 09:25:39 storageman.(*SLocalStorage).GetAvailSizeMb(storage_local.go:221)] Storage /opt/cloud/workspace/disks sizeMb 21746087, usablePercent 0.950000
[info 2024-04-09 09:25:39 storageman.(*SLocalStorage).SyncStorageInfo(storage_local.go:255)] Sync storage info /host_10.7.8.35_local_storage_0
[error 2024-04-09 09:25:39 storageman.(*SLocalStorage).SyncStorageInfo(storage_local.go:277)] SyncStorageInfo Failed: {"actual_capacity_used":169473,"capacity":21746087,"medium_type":"rotate","name":"host_10.7.8.35_local_storage_0","storage_type":"local","storagecache_id":"fc2035c8-ec01-4081-8a7b-bcd5d4a79db0","zone":"cf40e83b-ca3b-4bd3-83b7-050409c67b22"}: {"error":{"class":"DuplicateNameError","code":409,"details":"Duplicate name storage host_10.7.8.35_local_storage_0","request":{"body":"{\"storage\":{\"actual_capacity_used\":169473,\"capacity\":21746087,\"medium_type\":\"rotate\",\"name\":\"host_10...4bd3-83b7-050409c67b22\"}}","headers":{"Content-Length":"252","Content-Type":"application/json","User-Agent":"yunioncloud-go/201708","X-Auth-Token":"*","X-Yunion-Parent-Id":"","X-Yunion-Peer-Service-Name":"host","X-Yunion-Remote-Addr":"default-region:30888","X-Yunion-Span-Id":"0","X-Yunion-Span-Name":"","X-Yunion-Strace-Debug":"true","X-Yunion-Strace-Id":"4146d9f8"},"method":"POST","url":"https://default-region:30888/storages"}}}
[info 2024-04-09 09:25:39 hostinfo.(*SHostInfo).onSucc(hostinfo.go:2050)] Host registration process success....
[info 2024-04-09 09:25:39 guestman.(*SGuestManager).Bootstrap(guestman.go:240)] Loading existing guests ...
[info 2024-04-09 09:25:39 guestman.(*SGuestManager).OnLoadExistingGuestsComplete(guestman.go:311)] Load existing guests complete...
[error 2024-04-09 09:25:39 hostinfo.(*SHostInfo).PutHostOnline(hostinfo.go:1554)] Host sys error: map[isolated_devices:[{isolated_devices    GPU 02:00.0 use kernel driver ast, skip it 2024-04-09 09:25:39.863669218 +0000 UTC m=+4.613047339}] storages:[{storages   sync storage  failed: Storages.Create {"actual_capacity_used":169473,"capacity":21746087,"medium_type":"rotate","name":"host_10.7.8.35_local_storage_0","storage_type":"local","storagecache_id":"fc2035c8-ec01-4081-8a7b-bcd5d4a79db0","zone":"cf40e83b-ca3b-4bd3-83b7-050409c67b22"}: {"error":{"class":"DuplicateNameError","code":409,"details":"Duplicate name storage host_10.7.8.35_local_storage_0","request":{"body":"{\"storage\":{\"actual_capacity_used\":169473,\"capacity\":21746087,\"medium_type\":\"rotate\",\"name\":\"host_10...4bd3-83b7-050409c67b22\"}}","headers":{"Content-Length":"252","Content-Type":"application/json","User-Agent":"yunioncloud-go/201708","X-Auth-Token":"*","X-Yunion-Parent-Id":"","X-Yunion-Peer-Service-Name":"host","X-Yunion-Remote-Addr":"default-region:30888","X-Yunion-Span-Id":"0","X-Yunion-Span-Name":"","X-Yunion-Strace-Debug":"true","X-Yunion-Strace-Id":"4146d9f8"},"method":"POST","url":"https://default-region:30888/storages"}}} 2024-04-09 09:25:39.915852157 +0000 UTC m=+4.665230279}]]
[info 2024-04-09 09:25:39 hostinfo.(*SHostPingTask).Start(hostpinger.go:76)] Start host pinger ...
```

**Comment by wanyaoqi** [comment]
> {"error":{"class":"DuplicateNameError","code":409,"details":"Duplicate name storage host_10.7.8.35_local_storage_0",

@weiwhy 你先尝试使用 climc storage-delete storage host_10.7.8.35_local_storage_0 ，然后再重启host服务

**Comment by weiwhy** [comment]
解决了，telegraf正常启动了，显示也正常了

**Comment by weiwhy** [comment]
感谢大佬
