### ISSUE TITLE
[BUG]在阿里云上开了一台虚拟机， 部署， cloudpods 私有云， 有以下报错

### ISSUE THREAD

**Issue by khw934** [yunionio/cloudpods#20160]
**问题描述/What happened**:

在阿里云上开了一台虚拟机， 部署， cloudpods 私有云， 有以下报错

[info 2024-04-28 05:05:08 hostinfo.(*SHostInfo).detectOvsVersion(hostinfo.go:993)] Detect OVS version is 2.12.4
[info 2024-04-28 05:05:08 hostinfo.(*SHostInfo).detectOvsKOVersion(hostinfo.go:1010)] kernel module openvswitch vermagic:       3.10.0-1160.el7.x86_64 SMP mod_unload modversions
[info 2024-04-28 05:05:08 hostinfo.(*SHostInfo).Init(hostinfo.go:205)] Start parseConfig
[info 2024-04-28 05:05:08 hostinfo.NewNIC(hostinfohelper.go:241)] IP 10.0.0.4/br0/eth0
[info 2024-04-28 05:05:08 hostbridge.(*SBaseBridgeDriver).ConfirmToConfig(hostbridge.go:180)] bridge br0 already has ip 10.0.0.4
[info 2024-04-28 05:05:09 hostinfo.NewNIC(hostinfohelper.go:291)] Confirm to configuration!!
[info 2024-04-28 05:05:09 hostinfo.(*SNIC).SetupDhcpRelay(hostinfohelper.go:203)] Not enable dhcp relay on nic: &hostinfo.SNIC{Inter:"eth0", Bridge:"br0", Ip:"10.0.0.4", Wire:"", WireId:"", Mask:24, Bandwidth:1000, BridgeDev:(*hostbridge.SOVSBridgeDriver)(0xc000c60de0), dhcpServer:(*hostdhcp.SGuestDHCPServer)(0xc000c61980)}
[info 2024-04-28 05:05:09 hostinfo.(*SHostInfo).setupOvnChassis(hostinfo.go:223)] Start setting up ovn chassis
[error 2024-04-28 05:05:09 auth.(*authManager).startRefreshRevokeTokens(auth.go:193)] refreshRevokeTokens: No valid admin token credential
[info 2024-04-28 05:05:09 hostman.(*SHostService).RunService.func1(host_services.go:85)] Auth complete!!
[info 2024-04-28 05:05:09 policy.(*SPolicyManager).init(policy.go:160)] policy fetch worker count 1
[info 2024-04-28 05:05:09 consts.SetNonDefaultDomainProjects(consts.go:109)] set non_default_domain_projects to false
[info 2024-04-28 05:05:09 options.StartOptionManagerWithSessionDriver(manager.go:68)] OptionManager start to fetch service configs with interval 30m0s ...
[info 2024-04-28 05:05:09 watcher.(*SInformerSyncManager).startWatcher(watcher.go:83)]EndpointChangeManager: Start resource informer watcher for endpoint
[info 2024-04-28 05:05:09 options.optionsEquals(manager.go:120)] Options added: {"api_server":"https://10.0.0.4"}
[info 2024-04-28 05:05:09 watcher.(*SInformerSyncManager).startWatcher(watcher.go:83)]ServiceConfigManager: Start resource informer watcher for service
[info 2024-04-28 05:05:09 guestman.(*SGuestManager).InitQemuMaxCpus(guestman.go:147)] KVM max cpus count: 0
[info 2024-04-28 05:05:09 guestman.(*SGuestManager).InitQemuMaxCpus(guestman.go:165)] Machine type pc max cpus: 240
[info 2024-04-28 05:05:09 guestman.(*SGuestManager).InitQemuMaxCpus(guestman.go:165)] Machine type q35 max cpus: 240
[info 2024-04-28 05:05:09 informer.(*EtcdBackendForClient).StartClientWatch(etcd_client.go:84)] /onecloud/informer watched
[info 2024-04-28 05:05:09 guestman.(*SGuestManager).InitPythonPath.func1(guestman.go:180)] Python path /usr/bin/python
[info 2024-04-28 05:05:09 informer.NewWatchManagerBySessionBg.func1(watcher.go:51)] callback with watchMan success.
[info 2024-04-28 05:05:09 informer.(*EtcdBackendForClient).StartClientWatch(etcd_client.go:84)] /onecloud/informer watched
[info 2024-04-28 05:05:09 informer.NewWatchManagerBySessionBg.func1(watcher.go:51)] callback with watchMan success.
[info 2024-04-28 05:05:11 hostinfo.(*SHostInfo).ensureMasterNetworks(hostinfo.go:1208)] Master ip 10.0.0.4 to fetch wire
[info 2024-04-28 05:05:11 hostinfo.(*SHostInfo).tryCreateNetworkOnWire(hostinfo.go:1179)] Get master ip 10.0.0.4 and mask 24
[error 2024-04-28 05:05:11 hostinfo.(*SHostInfo).onFail(hostinfo.go:1105)] register failed: initHostRecords: initHostRecord: try create network: find_matched == false: InvalidStatusError
panic: exit immediately for retry...

goroutine 1 [running]:
yunion.io/x/onecloud/pkg/hostman/hostinfo.(*SHostInfo).onFail(0xc0000f82c0, {0x363b740?, 0xc000a93a70?})
        /root/go/src/yunion.io/x/onecloud/pkg/hostman/hostinfo/hostinfo.go:1108 +0x44a
yunion.io/x/onecloud/pkg/hostman/hostinfo.(*SHostInfo).register(0xc0000f82c0)
        /root/go/src/yunion.io/x/onecloud/pkg/hostman/hostinfo/hostinfo.go:1072 +0x6d
yunion.io/x/onecloud/pkg/hostman/hostinfo.(*SHostInfo).StartRegister(0xc00013c630?, 0xc000729800?)
        /root/go/src/yunion.io/x/onecloud/pkg/hostman/hostinfo/hostinfo.go:1049 +0x32
yunion.io/x/onecloud/pkg/hostman.(*SHostService).RunService(0xc000a47a30?)
        /root/go/src/yunion.io/x/onecloud/pkg/hostman/host_services.go:107 +0x2df
yunion.io/x/onecloud/pkg/cloudcommon/service.(*SServiceBase).StartService(0xc000a92858)
        /root/go/src/yunion.io/x/onecloud/pkg/cloudcommon/service/services.go:58 +0xe4
yunion.io/x/onecloud/pkg/hostman.StartService(...)
        /root/go/src/yunion.io/x/onecloud/pkg/hostman/host_services.go:163
main.main()
        /root/go/src/yunion.io/x/onecloud/cmd/host/main.go:30 +0x10a

**环境/Environment**:

- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Host: (e.g. `dmidecode | egrep -i 'manufacturer|product' |sort -u`)
- Service Version (e.g. `kubectl exec -n onecloud $(kubectl get pods -n onecloud | grep climc | awk '{print $1}') -- climc version-list`):

**Comment by khw934** [comment]
子网不能 是 10.0.0.0
