### ISSUE TITLE
[求助/Help]

### ISSUE THREAD

**Issue by tomorrrow666** [yunionio/cloudpods#21068]
ubuntu@k8sprimary:~/ocboot-master$ ./ocboot.py install ./config-k8s-ha.yml
Traceback (most recent call last):
  File "/home/ubuntu/ocboot-master/./ocboot.py", line 44, in <module>
    sys.exit(main())
  File "/home/ubuntu/ocboot-master/./ocboot.py", line 40, in main
    args.func(args)
  File "/home/ubuntu/ocboot-master/lib/install.py", line 58, in do_install
    raise e
  File "/home/ubuntu/ocboot-master/lib/install.py", line 54, in do_install
    return start(args.config)
  File "/home/ubuntu/ocboot-master/lib/install.py", line 89, in start
    config = ocboot.load_config(config_file)
  File "/home/ubuntu/ocboot-master/lib/ocboot.py", line 54, in load_config
    return OcbootConfig(config)
  File "/home/ubuntu/ocboot-master/lib/ocboot.py", line 92, in __init__
    self.primary_master_config = self._fetch_conf(PrimaryMasterConfig)
  File "/home/ubuntu/ocboot-master/lib/ocboot.py", line 139, in _fetch_conf
    return config_cls(Config(group_config), self.bastion_host)
  File "/home/ubuntu/ocboot-master/lib/ocboot.py", line 459, in __init__
    super(PrimaryMasterConfig, self).__init__(config)
  File "/home/ubuntu/ocboot-master/lib/ocboot.py", line 408, in __init__
    self.keepalived_router_id = int(self.high_availability_vip.replace('.', '')) % 255
ValueError: invalid literal for int() with base 10: '$K8S_VIP'

**Comment by swordqiu** [comment]
@tomorrrow666 是否方便把 config-k8s-ha.yml 去掉敏感信息上传？

**Comment by tomorrrow666** [comment]
# primary_master_node 表示运行 k8s 和 Cloudpods 服务的节点
primary_master_node:
  # ssh login IP
  hostname: $PRIMARY_IP
  # 不使用本地登录方式
  use_local: false
  # ssh login user
  user: root
  # cloudpods version
  onecloud_version: "v3.11.6"
  # mariadb connection address
  db_host: "$DB_IP"
  # mariadb user
  db_user: "$DB_USER"
  # mariadb password
  db_password: "$DB_PSWD"
  # mariadb port
  db_port: "$DB_PORT"
  # 节点服务监听的地址，多网卡时可以指定对应网卡的地址
  node_ip: "$PRIMARY_IP"
  # 对应 Kubernetes calico 插件默认网卡选择规则
  ip_autodetection_method: "can-reach=$PRIMARY_IP"
  # K8s 控制节点的 IP，对应keepalived 监听的 VIP
  controlplane_host: $K8S_VIP
  # K8s 控制节点 apiserver 监听的端口
  controlplane_port: "6443"
  # 该节点作为 Cloudpods 私有云计算节点，如果不想让控制节点作为计算节点，可以设置为 false
  as_host: true
  # 虚拟机可作为 Cloudpods 内置私有云计算节点（默认为 false）。开启此项时，请确保 as_host: true
  as_host_on_vm: true
  # 产品版本，从 [Edge, CMP, FullStack] 选择一个，FullStack 会安装融合云，CMP 安装多云管理版本，Edge 安装私有云
  product_version: 'Edge'
  # 服务对应的镜像仓库，如果待部署的机器不在中国大陆，可以用 dockerhub 的镜像仓库：docker.io/yunion
  image_repository: registry.cn-beijing.aliyuncs.com/yunion
  # 启用高可用模式
  high_availability: true
  # 使用 minio 作为后端虚拟机镜像存储
  enable_minio: true
  ha_using_local_registry: false
  # 计算节点默认网桥 br0 对应的网卡
  host_networks: "$PRIMARY_INTERFACE/br0/$PRIMARY_IP"

master_nodes:
  # 加入控制节点的 k8s vip
  controlplane_host: $K8S_VIP
  # 加入控制节点的 K8s apiserver 端口
  controlplane_port: "6443"
  # 作为 K8s 和 Cloudpods 控制节点
  as_controller: true
  # 该节点作为 Cloudpods 私有云计算节点，如果不想让控制节点作为计算节点，可以设置为 false
  as_host: true
  # 虚拟机可作为 Cloudpods 内置私有云计算节点（默认为 false）。开启此项时，请确保 as_host: true
  as_host_on_vm: true
  # 从 primary 节点同步 ntp 时间
  ntpd_server: "$PRIMARY_IP"
  # 启用高可用模式
  high_availability: true
  hosts:
  - user: root
    hostname: "$MASTER_1_IP"
    # 计算节点默认网桥 br0 对应的网卡
    host_networks: "$MASTER_1_INTERFACE/br0/$MASTER_1_IP"
  - user: root
    hostname: "$MASTER_2_IP"
    # 计算节点默认网桥 br0 对应的网卡
    host_networks: "$MASTER_2_INTERFACE/br0/$MASTER_2_IP"

**Comment by swordqiu** [comment]
@tomorrrow666 可能文档没有说清楚，yaml里的$开头的都是一些变量，可以认为文档提供的这个yaml只是一个模板，在使用时需要把这些变量替换为您的场景的实际的值。比如PRIMARY_IP是高可用主节点的IP地址。

**Comment by tomorrrow666** [comment]
DB_IP="10.127.190.11"
DB_PORT=3306
DB_PSWD="0neC1oudDB#"
DB_USER=root

K8S_VIP=10.127.190.10
PRIMARY_INTERFACE="eth0"
PRIMARY_IP=10.127.90.101

MASTER_1_INTERFACE="eth0"
MASTER_1_IP=10.127.90.102
MASTER_2_INTERFACE="eth0"
MASTER_2_IP=10.127.90.103
这些变量是写一个shell，放安装目录下么？

**Comment by swordqiu** [comment]
@tomorrrow666 把yaml文件里的变量替换成上面的值，然后再运行ocboot

**Comment by tomorrrow666** [comment]
主机名改成这几个？
k8s primary 
k8s master 1
k8s master 2
DB   有空格么？

但是还有其他yml文件也用了$变量了，

</body>
</html>

**Comment by zexi** [comment]
@tomorrrow666 另外麻烦提 issue 的时候加上标题。

**Comment by zexi** [comment]
相同问题：https://github.com/yunionio/cloudpods/issues/21064

**Comment by tomorrrow666** [comment]
TASK [primary-master-node/setup_k8s : Use ocadm init first master node] ********
fatal: [192.168.231.132]: FAILED! => {"changed": true, "cmd": "/opt/yunion/bin/ocadm init --control-plane-endpoint 192.168.230.1:6443 --mysql-host 192.168.231.136 --mysql-user root --mysql-password 0neC1oudDb# --mysql-port 3306 --image-repository registry.cn-beijing.aliyuncs.com/yunion --apiserver-advertise-address 192.168.231.132  --node-ip 192.168.231.132 --host-networks ens33/br0/192.168.231.132  --enable-hugepage --onecloud-version v3.11.6 --operator-version v3.11.6 --pod-network-cidr 10.40.0.0/16 --service-cidr 10.96.0.0/12 --service-dns-domain cluster.local --addon-calico-ip-autodetection-method can-reach=192.168.231.132 --high-availability-vip 192.168.230.1 --keepalived-version-tag v2.0.25 --enable-host-agent\n", "delta": "0:00:00.055953", "end": "2024-08-22 14:59:14.427135", "msg": "non-zero return code", "rc": 1, "start": "2024-08-22 14:59:14.371182", "stderr": "error execution phase preflight: [preflight] Some fatal errors occurred:\n\t[ERROR Mysql]: show grants for root@%: Error 1130: Host '192.168.231.132' is not allowed to connect to this MariaDB server\n[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`", "stderr_lines": ["error execution phase preflight: [preflight] Some fatal errors occurred:", "\t[ERROR Mysql]: show grants for root@%: Error 1130: Host '192.168.231.132' is not allowed to connect to this MariaDB server", "[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`"], "stdout": "[init] Using Kubernetes and Onecloud version: v1.15.8 & v3.11.6\n[preflight] Running pre-flight checks", "stdout_lines": ["[init] Using Kubernetes and Onecloud version: v1.15.8 & v3.11.6", "[preflight] Running pre-flight checks"]}

**Comment by zexi** [comment]
> [ERROR Mysql]: show grants for root@%: Error 1130: Host '192.168.231.132' is not allowed to connect to this MariaDB server", 

需要排查 mysql 能否正常连接

**Comment by tomorrrow666** [comment]
TASK [common : init apt cache for Ubuntu] **************************************
fatal: [192.168.231.132]: FAILED! => {"changed": false, "dest": "/tmp/yunion.gpg-key.asc", "elapsed": 20, "msg": "Request failed: <urlopen error [Errno -3] 域名解析出现暂时性错误>", "url": "https://iso.yunion.cn/ubuntu/22/base/x86_64/yunion.gpg-key.asc"}
fatal: [192.168.231.134]: FAILED! => {"changed": false, "dest": "/tmp/yunion.gpg-key.asc", "elapsed": 20, "msg": "Request failed: <urlopen error [Errno -3] 域名解析出现暂时性错误>", "url": "https://iso.yunion.cn/ubuntu/22/base/x86_64/yunion.gpg-key.asc"}
fatal: [192.168.231.133]: FAILED! => {"changed": false, "dest": "/tmp/yunion.gpg-key.asc", "elapsed": 20, "msg": "Request failed: <urlopen error [Errno -3] 域名解析出现暂时性错误>", "url": "https://iso.yunion.cn/ubuntu/22/base/x86_64/yunion.gpg-key.asc"}

NO MORE HOSTS LEFT *************************************************************

**Comment by tomorrrow666** [comment]
TASK [utils/detect-os : stat k3s bin] ******************************************
[WARNING]: Unhandled error in Python interpreter discovery for host
192.168.43.139: Failed to connect to the host via ssh: ssh: connect to host
192.168.43.1 port 22: Connection timed out
[WARNING]: Unhandled error in Python interpreter discovery for host
192.168.43.140: Failed to connect to the host via ssh: ssh: connect to host
192.168.43.1 port 22: Connection timed out
[WARNING]: Unhandled error in Python interpreter discovery for host
192.168.43.138: Failed to connect to the host via ssh: ssh: connect to host
192.168.43.1 port 22: Connection timed out
fatal: [192.168.43.139 -> 192.168.43.1]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.43.1\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.43.1 port 22: Connection timed out\r\n", "unreachable": true}
fatal: [192.168.43.138 -> 192.168.43.1]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.43.1\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.43.1 port 22: Connection timed out\r\n", "unreachable": true}
fatal: [192.168.43.140 -> 192.168.43.1]: UNREACHABLE! => {"changed": false, "msg": "Data could not be sent to remote host \"192.168.43.1\". Make sure this host can be reached over ssh: ssh: connect to host 192.168.43.1 port 22: Connection timed out\r\n", "unreachable": true}

**Comment by tomorrrow666** [comment]
TASK [primary-master-node/setup_k8s : Use ocadm init first master node] ********
fatal: [192.168.43.138]: FAILED! => {"changed": true, "cmd": "/opt/yunion/bin/ocadm init --control-plane-endpoint 192.168.43.1:6443 --mysql-host 192.168.43.141 --mysql-user root --mysql-password 0neC1oudDB# --mysql-port 3306 --image-repository registry.cn-beijing.aliyuncs.com/yunion --apiserver-advertise-address 192.168.43.138  --node-ip 192.168.43.138 --host-networks ens33/br0/192.168.43.138  --enable-hugepage --onecloud-version v3.11.6 --operator-version v3.11.6 --pod-network-cidr 10.40.0.0/16 --service-cidr 10.96.0.0/12 --service-dns-domain cluster.local --addon-calico-ip-autodetection-method can-reach=192.168.43.138 --high-availability-vip 192.168.43.1 --keepalived-version-tag v2.0.25 --enable-host-agent\n", "delta": "0:00:00.315037", "end": "2024-08-25 21:27:33.214740", "msg": "non-zero return code", "rc": 1, "start": "2024-08-25 21:27:32.899703", "stderr": "\t[WARNING SystemVerification]: this Docker version is not on the list of validated versions: 20.10.24. Latest validated version: 18.09\nerror execution phase preflight: k8s init node checks: [preflight] Some fatal errors occurred:\n\t[ERROR SystemVerification]: unsupported kernel release: 6.8.0-40-generic\n[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`", "stderr_lines": ["\t[WARNING SystemVerification]: this Docker version is not on the list of validated versions: 20.10.24. Latest validated version: 18.09", "error execution phase preflight: k8s init node checks: [preflight] Some fatal errors occurred:", "\t[ERROR SystemVerification]: unsupported kernel release: 6.8.0-40-generic", "[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`"], "stdout": "[init] Using Kubernetes and Onecloud version: v1.15.8 & v3.11.6\n[preflight] Running pre-flight checks\n[preflight] The system verification failed. Printing the output from the verification:\n\u001b[0;37mKERNEL_VERSION\u001b[0m: \u001b[0;31m6.8.0-40-generic\u001b[0m\n\u001b[0;37mCONFIG_NAMESPACES\u001b[0m: \u001b[0;32menabled\u001b[0m\n\u001b[0;37mCONFIG_NET_NS\u001b[0m: \u001b[0;32menabled\u001b[0m\n\u001b[0;37mCONFIG_PID_NS\u001b[0m: \u001b[0;32menabled\u001b[0m\n\u001b[0;37mCONFIG_IPC_NS\u001b[0m: \u001b[0;32menabled\u001b[0m\n\u001b[0;37mCONFIG_UTS_NS\u001b[0m: \u001b[0;32menabled\u001b[0m\n\u001b[0;37mCONFIG_CGROUPS\u001b[0m: \u001b[0;32menabled\u001b[0m\n\u001b[0;37mCONFIG_CGROUP_CPUACCT\u001b[0m: \u001b[0;32menabled\u001b[0m\n\u001b[0;37mCONFIG_CGROUP_DEVICE\u001b[0m: \u001b[0;32menabled\u001b[0m\n\u001b[0;37mCONFIG_CGROUP_FREEZER\u001b[0m: \u001b[0;32menabled\u001b[0m\n\u001b[0;37mCONFIG_CGROUP_SCHED\u001b[0m: \u001b[0;32menabled\u001b[0m\n\u001b[0;37mCONFIG_CPUSETS\u001b[0m: \u001b[0;32menabled\u001b[0m\n\u001b[0;37mCONFIG_MEMCG\u001b[0m: \u001b[0;32menabled\u001b[0m\n\u001b[0;37mCONFIG_INET\u001b[0m: \u001b[0;32menabled\u001b[0m\n\u001b[0;37mCONFIG_EXT4_FS\u001b[0m: \u001b[0;32menabled\u001b[0m\n\u001b[0;37mCONFIG_PROC_FS\u001b[0m: \u001b[0;32menabled\u001b[0m\n\u001b[0;37mCONFIG_NETFILTER_XT_TARGET_REDIRECT\u001b[0m: \u001b[0;32menabled (as module)\u001b[0m\n\u001b[0;37mCONFIG_NETFILTER_XT_MATCH_COMMENT\u001b[0m: \u001b[0;32menabled (as module)\u001b[0m\n\u001b[0;37mCONFIG_OVERLAY_FS\u001b[0m: \u001b[0;32menabled (as module)\u001b[0m\n\u001b[0;37mCONFIG_AUFS_FS\u001b[0m: \u001b[0;33mnot set - Required for aufs.\u001b[0m\n\u001b[0;37mCONFIG_BLK_DEV_DM\u001b[0m: \u001b[0;32menabled\u001b[0m\n\u001b[0;37mDOCKER_VERSION\u001b[0m: \u001b[0;32m20.10.24\u001b[0m\n\u001b[0;37mOS\u001b[0m: \u001b[0;32mLinux\u001b[0m\n\u001b[0;37mCGROUPS_CPU\u001b[0m: \u001b[0;32menabled\u001b[0m\n\u001b[0;37mCGROUPS_CPUACCT\u001b[0m: \u001b[0;32menabled\u001b[0m\n\u001b[0;37mCGROUPS_CPUSET\u001b[0m: \u001b[0;32menabled\u001b[0m\n\u001b[0;37mCGROUPS_DEVICES\u001b[0m: \u001b[0;32menabled\u001b[0m\n\u001b[0;37mCGROUPS_FREEZER\u001b[0m: \u001b[0;32menabled\u001b[0m\n\u001b[0;37mCGROUPS_MEMORY\u001b[0m: \u001b[0;32menabled\u001b[0m", "stdout_lines": ["[init] Using Kubernetes and Onecloud version: v1.15.8 & v3.11.6", "[preflight] Running pre-flight checks", "[preflight] The system verification failed. Printing the output from the verification:", "\u001b[0;37mKERNEL_VERSION\u001b[0m: \u001b[0;31m6.8.0-40-generic\u001b[0m", "\u001b[0;37mCONFIG_NAMESPACES\u001b[0m: \u001b[0;32menabled\u001b[0m", "\u001b[0;37mCONFIG_NET_NS\u001b[0m: \u001b[0;32menabled\u001b[0m", "\u001b[0;37mCONFIG_PID_NS\u001b[0m: \u001b[0;32menabled\u001b[0m", "\u001b[0;37mCONFIG_IPC_NS\u001b[0m: \u001b[0;32menabled\u001b[0m", "\u001b[0;37mCONFIG_UTS_NS\u001b[0m: \u001b[0;32menabled\u001b[0m", "\u001b[0;37mCONFIG_CGROUPS\u001b[0m: \u001b[0;32menabled\u001b[0m", "\u001b[0;37mCONFIG_CGROUP_CPUACCT\u001b[0m: \u001b[0;32menabled\u001b[0m", "\u001b[0;37mCONFIG_CGROUP_DEVICE\u001b[0m: \u001b[0;32menabled\u001b[0m", "\u001b[0;37mCONFIG_CGROUP_FREEZER\u001b[0m: \u001b[0;32menabled\u001b[0m", "\u001b[0;37mCONFIG_CGROUP_SCHED\u001b[0m: \u001b[0;32menabled\u001b[0m", "\u001b[0;37mCONFIG_CPUSETS\u001b[0m: \u001b[0;32menabled\u001b[0m", "\u001b[0;37mCONFIG_MEMCG\u001b[0m: \u001b[0;32menabled\u001b[0m", "\u001b[0;37mCONFIG_INET\u001b[0m: \u001b[0;32menabled\u001b[0m", "\u001b[0;37mCONFIG_EXT4_FS\u001b[0m: \u001b[0;32menabled\u001b[0m", "\u001b[0;37mCONFIG_PROC_FS\u001b[0m: \u001b[0;32menabled\u001b[0m", "\u001b[0;37mCONFIG_NETFILTER_XT_TARGET_REDIRECT\u001b[0m: \u001b[0;32menabled (as module)\u001b[0m", "\u001b[0;37mCONFIG_NETFILTER_XT_MATCH_COMMENT\u001b[0m: \u001b[0;32menabled (as module)\u001b[0m", "\u001b[0;37mCONFIG_OVERLAY_FS\u001b[0m: \u001b[0;32menabled (as module)\u001b[0m", "\u001b[0;37mCONFIG_AUFS_FS\u001b[0m: \u001b[0;33mnot set - Required for aufs.\u001b[0m", "\u001b[0;37mCONFIG_BLK_DEV_DM\u001b[0m: \u001b[0;32menabled\u001b[0m", "\u001b[0;37mDOCKER_VERSION\u001b[0m: \u001b[0;32m20.10.24\u001b[0m", "\u001b[0;37mOS\u001b[0m: \u001b[0;32mLinux\u001b[0m", "\u001b[0;37mCGROUPS_CPU\u001b[0m: \u001b[0;32menabled\u001b[0m", "\u001b[0;37mCGROUPS_CPUACCT\u001b[0m: \u001b[0;32menabled\u001b[0m", "\u001b[0;37mCGROUPS_CPUSET\u001b[0m: \u001b[0;32menabled\u001b[0m", "\u001b[0;37mCGROUPS_DEVICES\u001b[0m: \u001b[0;32menabled\u001b[0m", "\u001b[0;37mCGROUPS_FREEZER\u001b[0m: \u001b[0;32menabled\u001b[0m", "\u001b[0;37mCGROUPS_MEMORY\u001b[0m: \u001b[0;32menabled\u001b[0m"]}

**Comment by tomorrrow666** [comment]
https://github.com/yunionio/

**Comment by tomorrrow666** [comment]
ok: [192.168.125.132] => (item=[02/37] yunion-climc=3.11*)
failed: [192.168.125.129] (item=[02/37] yunion-climc=3.11*) => {"ansible_index_var": "item_index", "ansible_loop_var": "package_item", "cache_update_time": 1724640218, "cache_updated": false, "changed": false, "item_index": 1, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"       install 'yunion-climc=3.11.6-24081720'' failed: E: 降级软件包同时使用了 -y 选项，但是没有用 --allow-downgrades.\n", "package_item": "yunion-climc=3.11*", "rc": 100, "stderr": "E: 降级软件包同时使用了 -y 选项，但是没有用 --allow-downgrades.\n", "stderr_lines": ["E: 降级软件包同时使用了 -y 选项，但是没有用 --allow-downgrades."], "stdout": "正在读取软件包列表...\n正在分析软件包的依赖关系树...\n正在读取状态信息...\n下列软件包是自动安装的并且现在不需要了：\n  ieee-data python3-argcomplete python3-dnspython python3-libcloud\n  python3-netaddr python3-pycryptodome python3-requests-toolbelt\n  python3-simplejson\n使用'apt autoremove'来卸载它(它们)。\n下列 软件包将被【降级】：\n  yunion-climc\n升级了 0 个软件包，新安装了 0 个软件包，降级了 1 个软件包，要卸载 0 个软件包，有 13 个软件包未被升级。\n", "stdout_lines": ["正 在读取软件包列表...", "正在分析软件包的依赖关系树...", "正在读取状态信息...", "下列软件包是自动安装的并且现在不需要了：", "  ieee-data python3-argcomplete python3-dnspython python3-libcloud", "  python3-netaddr python3-pycryptodome python3-requests-toolbelt", "  python3-simplejson", "使用'apt autoremove'来卸载它(它们)。", "下列软 件包将被【降级】：", "  yunion-climc", "升级了 0 个软件包，新安装了 0 个软件包，降级了 1 个软件包，要卸载 0 个软件包，有 13 个软件包未被升级。"]}
