### ISSUE TITLE
[BUG] 部署失败

### ISSUE THREAD

**Issue by tocha688** [yunionio/cloudpods#21071]
Press any key to continue and then input root's password to 156.238.251.xxx

/bin/ssh-copy-id: INFO: Source of key(s) to be installed: "/root/.ssh/id_rsa.pub"
/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed

/bin/ssh-copy-id: ERROR: ssh: connect to host 156.238.251.xxx port 22: Connection refused

Configure passwordless ssh failed, please try to configure it manually
Traceback (most recent call last):
  File "./run.py", line 535, in <module>
    sys.exit(main())
  File "./run.py", line 530, in main
    check_env(ip_conf, pip_mirror=args.pip_mirror)
  File "./run.py", line 181, in check_env
    check_passless_ssh(ipaddr)
  File "./run.py", line 148, in check_passless_ssh
    raise e
  File "./run.py", line 145, in check_passless_ssh
    install_passless_ssh(ipaddr)
  File "./run.py", line 166, in install_passless_ssh
    raise Exception("ssh-copy-id")
Exception: ssh-copy-id

**Comment by zexi** [comment]
ssh 服务没有允许密码登录？

**Comment by tocha688** [comment]
加上密码登录的，问题是端口不是22，他默认是22端口连接

**Comment by zexi** [comment]
> 是密码登录的，问题是端口不是22，他默认是22端口连接

@tocha688 改下 ocboot 目录下面的 config-allinone-current.yml 文件，加上 port 的字段：
<img width="411" alt="image" src="https://github.com/user-attachments/assets/516247be-dd51-47d6-89c4-be8fc65b2c72">
然后再执行 ./run.py 脚本试试
