### ISSUE TITLE
[求助/Help]添加计算节点的问题

### ISSUE THREAD

**Issue by yiranlianji** [yunionio/cloudpods#21455]
部署的高可用版本v3.11.8，计划添加2台计算节点（操作系统都是一样的），通过文档操作，1台加成功了，可以通过climc host-list看到，另外1台看不到，多次卸载重新添加节点也不行。排查后发现的一些问题：
1. default-host容器一直`CrashLoopBackOff`，日志报`Host instance init error: Prepare environment: Failed to activate tun/tap device: grpc dial error: context deadline exceeded`
```sh
[root@localhost tasks]# kubectl logs -f -n onecloud default-host-rpwvf
Defaulted container "host" out of: host, ovn-controller, sdnagent
[info 241024 06:15:54 procutils.WaitZombieLoop(zombie_others.go:36)] My pid is not 1 and no need to wait zombies
[info 241024 06:15:54 options.parseOptions(options.go:337)] Use configuration file: /etc/yunion/host.conf
[warning 241024 06:15:54 structarg.(*ArgumentParser).parseJSONKeyValue(structarg.go:1215)] Cannot find argument start-host-ignore-sys-error
[warning 241024 06:15:54 structarg.(*ArgumentParser).parseJSONKeyValue(structarg.go:1215)] Cannot find argument enable-qmp-monitor
[warning 241024 06:15:54 structarg.(*ArgumentParser).parseJSONKeyValue(structarg.go:1215)] Cannot find argument disk-is-ssd
[warning 241024 06:15:54 structarg.(*ArgumentParser).parseJSONKeyValue(structarg.go:1215)] Cannot find argument enable-health-checker
[warning 241024 06:15:55 structarg.(*ArgumentParser).parseJSONKeyValue(structarg.go:1215)] Cannot find argument enable-rbac
[warning 241024 06:15:55 structarg.(*ArgumentParser).parseJSONKeyValue(structarg.go:1215)] Cannot find argument health-driver
[info 241024 06:15:55 options.parseOptions(options.go:360)] Set log level to "info"
[info 2024-10-24 06:15:55 options.parseOptions(options.go:337)] Use configuration file: /etc/yunion/common/common.conf
[info 2024-10-24 06:15:55 options.parseOptions(options.go:360)] Set log level to "info"
[info 2024-10-24 06:15:55 hostman.(*SHostService).InitService(host_services.go:64)] exec socket path: /var/run/onecloud/exec.sock
[info 2024-10-24 06:15:55 app.InitApp(app.go:32)] RequestWorkerCount: 8
[info 2024-10-24 06:15:55 appsrv.NewApplication(appsrv.go:121)] App hostId: 9FTNRc91XGkU1tGY9IwYdopXspk= (host,localhost,192.169.1.24)
2024/10/24 06:15:55 Allow hosts []
[info 2024-10-24 06:15:55 appsrv.(*Application).SetDefaultTimeout(appsrv.go:137)] adjust application default timeout to 60.000000 seconds
[info 2024-10-24 06:15:55 hostinfo.DetectCpuInfo(hostinfohelper.go:78)] cpuinfo freq 3000
[info 2024-10-24 06:15:55 hostinfo.NewHostInfo(hostinfo.go:2493)] CPU Model Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz Microcode 0x49
[error 2024-10-24 06:16:25 hostinfo.(*SHostInfo).prepareEnv(hostinfo.go:381)] tuned-adm profile virtual-host fail: grpc dial error: context deadline exceeded
[error 2024-10-24 06:16:25 fileutils2.GetAllBlkdevsIoSchedulers(fileutils.go:171)] no block device avaiable
[info 2024-10-24 06:16:25 hostinfo.(*SHostInfo).prepareEnv(hostinfo.go:412)] I/O Scheduler switch to none
goroutine 1 [running]:
runtime/debug.Stack()
        /usr/lib/go/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
        /usr/lib/go/src/runtime/debug/stack.go:16 +0x13
yunion.io/x/log.Fatalf({0x364ee7b, 0x1c}, {0xc00123fe70, 0x1, 0x1})
        /root/go/src/yunion.io/x/onecloud/vendor/yunion.io/x/log/log.go:138 +0x2c
yunion.io/x/onecloud/pkg/hostman.(*SHostService).RunService(0xc0005171e8?)
        /root/go/src/yunion.io/x/onecloud/pkg/hostman/host_services.go:81 +0xaa
yunion.io/x/onecloud/pkg/cloudcommon/service.(*SServiceBase).StartService(0xc0009a32d8)
        /root/go/src/yunion.io/x/onecloud/pkg/cloudcommon/service/services.go:58 +0xdf
yunion.io/x/onecloud/pkg/hostman.StartService(...)
        /root/go/src/yunion.io/x/onecloud/pkg/hostman/host_services.go:163
main.main()
        /root/go/src/yunion.io/x/onecloud/cmd/host/main.go:30 +0xec
[fatal 2024-10-24 06:16:55 hostman.(*SHostService).RunService(host_services.go:81)] Host instance init error: Prepare environment: Failed to activate tun/tap device: grpc dial error: context deadline exceeded
```
2. 查看网卡，没有br0，openvswitch服务没用启动
```shell
[root@localhost ~]# ip -4 -brief address show
lo               UNKNOWN        127.0.0.1/8 
team0            UP             192.168.1.24/24 
kube-ipvs0       DOWN           10.111.150.75/32 10.106.176.36/32 10.110.147.205/32 10.96.161.68/32 10.109.230.9/32 10.110.255.221/32 10.96.0.10/32 10.104.220.4/32 10.96.200.240/32 10.103.25.112/32 10.96.108.46/32 10.98.152.236/32 10.102.184.212/32 10.96.128.62/32 10.99.38.29/32 10.99.201.184/32 10.110.181.210/32 10.107.123.55/32 10.96.0.1/32 10.96.17.143/32 10.110.124.126/32 10.104.208.77/32 10.105.62.51/32 10.97.156.61/32 10.98.37.235/32 10.106.92.79/32 
tunl0@NONE       UNKNOWN        10.40.120.192/32
```
3. 部署日志
[1024-24-01.log](https://github.com/user-attachments/files/17502547/1024-24-01.log)

**Comment by zexi** [comment]
@yiranlianji 看下对应节点上的 `systemctl status yunion-executor` 服务有没有启动？

**Comment by yiranlianji** [comment]
> @yiranlianji 看下对应节点上的 `systemctl status yunion-executor` 服务有没有启动？

没有启动，之前也有尝试启动后再次部署，还是一样的结果。

**Comment by zexi** [comment]
> > @yiranlianji 看下对应节点上的 `systemctl status yunion-executor` 服务有没有启动？
> 
> 没有启动，之前也有尝试启动后再次部署，还是一样的结果。如果是这个服务没启动，正确的处理方法是什么？@zexi

`systemctl enable --now yunion-executor` 执行这个命令看下能否正常启动？

**Comment by yiranlianji** [comment]
> > > @yiranlianji 看下对应节点上的 `systemctl status yunion-executor` 服务有没有启动？
> > 
> > 
> > 没有启动，之前也有尝试启动后再次部署，还是一样的结果。如果是这个服务没启动，正确的处理方法是什么？@zexi
> 
> `systemctl enable --now yunion-executor` 执行这个命令看下能否正常启动？

yunion-executor启动后，再启动openvswitch服务后，就可以了。
