### ISSUE TITLE
[求助/Help]重启宿主机服务不能起来，default-etcd  Init:0/1

### ISSUE THREAD

**Issue by chenjacken** [yunionio/cloudpods#21797]
所有控制节点服务器重启后，服务无法启动起来，大部分pod不能正常运行起来。
咨询下服务启动顺序是怎么的？我该如何排查问题。谢谢！

日志信息：

主控制节点POD状态：
```
[root@master1 ~]# kubectl get pods -n onecloud -owide |grep master1
default-apigateway-7ccd7c748d-x5r2q         0/1     CrashLoopBackOff        1200 (4m39s ago)   22d     10.40.137.97    master1    <none>           <none>
default-cloudevent-86f896f4fd-vktk5         0/1     CrashLoopBackOff        65 (4m46s ago)     5h23m   10.40.137.86    master1    <none>           <none>
default-cloudmon-647775f879-64crq           0/1     CrashLoopBackOff        65 (4m32s ago)     5h23m   10.40.137.79    master1    <none>           <none>
default-cloudproxy-8544ddf9f-q4tfb          0/1     Error                   66 (5m34s ago)     5h23m   10.40.137.80    master1    <none>           <none>
default-devtool-697b8fc485-wkm44            0/1     CrashLoopBackOff        65 (5m1s ago)      5h23m   10.40.137.111   master1    <none>           <none>
default-etcd-4l49xq8cls                     0/1     Init:0/1                0                  5h47m   10.40.137.76    master1    <none>           <none>
default-host-b62f4                          1/3     CrashLoopBackOff        2529 (71s ago)     26d     172.16.2.11     master1    <none>           <none>
default-host-deployer-tffzf                 0/1     CrashLoopBackOff        1242 (4m28s ago)   26d     172.16.2.11     master1    <none>           <none>
default-host-health-h79dg                   0/1     CrashLoopBackOff        1244 (17s ago)     26d     172.16.2.11     master1    <none>           <none>
default-host-image-rks9m                    0/1     CrashLoopBackOff        1242 (4m55s ago)   26d     172.16.2.11     master1    <none>           <none>
default-keystone-564c7d7677-9fx44           1/1     Running                 0                  5h23m   10.40.137.71    master1    <none>           <none>
default-kubeserver-7d6d486dff-kg8ld         0/1     Init:CrashLoopBackOff   66 (22s ago)       5h23m   10.40.137.82    master1    <none>           <none>
default-notify-84fd949f86-djn9p             0/1     Init:CrashLoopBackOff   65 (3m57s ago)     5h23m   10.40.137.89    master1    <none>           <none>
default-region-99c8ff56b-ntsnn              0/1     Init:CrashLoopBackOff   65 (4m22s ago)     5h23m   10.40.137.105   master1    <none>           <none>
default-region-dns-hpvrv                    0/1     Error                   1242 (5m6s ago)    26d     172.16.2.11     master1    <none>           <none>
default-telegraf-t22xh                      1/1     Running                 6 (5h50m ago)      26d     172.16.2.11     master1    <none>           <none>
default-web-7864bd644b-zdnq2                0/1     CrashLoopBackOff        68 (22s ago)       5h23m   10.40.137.104   master1    <none>           <none>
default-yunionconf-db568c8bd-qglpf          1/1     Running                 66 (5m22s ago)     5h23m   10.40.137.94    master1    <none>           <none>
onecloud-operator-5755bfbb9c-mm7qx          1/1     Running                 0                  5h23m   10.40.137.92    master1    <none>           <none>
[root@master1 ~]# 
```

default-etcd一直在PodInitializing
```
[root@master1 ~]# kubectl logs  default-etcd-4l49xq8cls -n onecloud
Defaulted container "etcd" out of: etcd, check-dns (init)
Error from server (BadRequest): container "etcd" in pod "default-etcd-4l49xq8cls" is waiting to start: PodInitializing
[root@master1 ~]# 
```

default-keystone的日志：
```
[root@master1 ~]# kubectl logs default-keystone-564c7d7677-7brfq -n onecloud
Defaulted container "keystone" out of: keystone, init (init)
[info 241212 16:12:32 options.parseOptions(options.go:337)] Use configuration file: /etc/yunion/keystone.conf
[warning 241212 16:12:32 structarg.(*ArgumentParser).parseJSONKeyValue(structarg.go:1215)] Cannot find argument fernet-key-repository
[warning 241212 16:12:32 structarg.(*ArgumentParser).parseJSONKeyValue(structarg.go:1215)] Cannot find argument setup-credential-keys
[warning 241212 16:12:32 structarg.(*ArgumentParser).parseJSONKeyValue(structarg.go:1215)] Cannot find argument token-expiration-seconds
[info 241212 16:12:32 options.parseOptions(options.go:360)] Set log level to "info"
[info 2024-12-12 16:12:32 app.InitApp(app.go:32)] RequestWorkerCount: 8
[info 2024-12-12 16:12:32 appsrv.NewApplication(appsrv.go:121)] App hostId: f46AzxJmew1cD6gmm8HX3CGlo_s= (identity,default-keystone-564c7d7677-7brfq,10.40.180.38)
2024/12/12 16:12:32 Allow hosts []
[info 2024-12-12 16:12:32 appsrv.(*Application).SetDefaultTimeout(appsrv.go:137)] adjust application default timeout to 60.000000 seconds
[info 2024-12-12 16:12:32 cloudcommon.InitDB(database.go:48)] Registered SQL drivers: clickhouse, dm, mysql, sqlite3
[info 2024-12-12 16:12:32 cloudcommon.InitDB(database.go:88)] database dialect: mysql sqlStr: keystone:aTStHm7cDsG3fgKT@tcp(172.16.2.99:3306)/keystone?charset=utf8&parseTime=True
[info 2024-12-12 16:12:32 cloudcommon.InitDB(database.go:122)] using inmemory lockman
[info 2024-12-12 16:12:32 db.CheckSync(models.go:116)] Start check database schema: autoSync(false), enableChecksumTables(false), skipInitChecksum(false)
[info 2024-12-12 16:12:33 db.setDbConnection(database.go:60)] Total 26 db workers, set db connection max
[info 2024-12-12 16:12:33 policy.(*SPolicyManager).init(policy.go:160)] policy fetch worker count 1
[info 2024-12-12 16:12:33 consts.SetNonDefaultDomainProjects(consts.go:109)] set non_default_domain_projects to false
[info 2024-12-12 16:12:33 options.StartOptionManagerWithSessionDriver(manager.go:68)] OptionManager start to fetch service configs with interval 30m0s ...
[info 2024-12-12 16:12:33 options.optionsEquals(manager.go:120)] Options added: {"api_server":"https://172.16.2.11"}
[info 2024-12-12 16:12:33 app.ServeForeverExtended(app.go:60)] Start listen on https://0.0.0.0:30500, isMaster: true
[info 2024-12-12 16:12:33 app.ServeForeverExtended(app.go:60)] Start listen on https://0.0.0.0:30357, isMaster: false
[error 2024-12-12 16:12:37 models.(*SEndpointManager).SetInformerBackendUntilSuccess.func1.1(endpoints.go:176)] Set etcd informer backend failed: new etcd informer backend: new etcd client: context deadline exceeded
[error 2024-12-12 16:13:12 models.(*SEndpointManager).SetInformerBackendUntilSuccess.func1.1(endpoints.go:176)] Set etcd informer backend failed: new etcd informer backend: new etcd client: context deadline exceeded
[error 2024-12-12 16:13:47 models.(*SEndpointManager).SetInformerBackendUntilSuccess.func1.1(endpoints.go:176)] Set etcd informer backend failed: new etcd informer backend: new etcd client: context deadline exceeded
[error 2024-12-12 16:14:22 models.(*SEndpointManager).SetInformerBackendUntilSuccess.func1.1(endpoints.go:176)] Set etcd informer backend failed: new etcd informer backend: new etcd client: context deadline exceeded
[root@master1 ~]# 
```

default-region一直不能起来
```
[root@master1 ~]# kubectl get pods -n onecloud -owide |grep region
default-region-6b6996454b-t6n69             0/1     Init:Error              75 (5m17s ago)     6h18m   10.40.136.43    master3    <none>           <none>
default-region-99c8ff56b-mkjtc              0/1     Init:Error              3 (47s ago)        93s     10.40.180.7     master2    <none>           <none>
default-region-dns-2n64b                    0/1     CrashLoopBackOff        1101 (59s ago)     26d     172.16.2.13     master3    <none>           <none>
default-region-dns-hpvrv                    0/1     Error                   1245 (5m26s ago)   26d     172.16.2.11     master1    <none>           <none>
default-region-dns-m9t8j                    0/1     CrashLoopBackOff        1241 (20s ago)     26d     172.16.2.12     master2    <none>           <none>
[root@master1 ~]# kubectl logs default-region-6b6996454b-t6n69 -n onecloud
Defaulted container "region" out of: region, init (init)
Error from server (BadRequest): container "region" in pod "default-region-6b6996454b-t6n69" is waiting to start: PodInitializing
[root@master1 ~]# 
```

default-cloudid的日志：
```
[root@master1 ~]# kubectl logs default-cloudid-7dd985ffdd-b5wxv -n onecloud
[info 241212 16:06:19 loader.init.0(loader.go:51)] Loading cloud providers ...
[info 241212 16:06:19 options.parseOptions(options.go:337)] Use configuration file: /etc/yunion/cloudid.conf
[info 241212 16:06:19 options.parseOptions(options.go:360)] Set log level to "info"
[error 2024-12-12 16:06:19 auth.(*authManager).startRefreshRevokeTokens(auth.go:193)] refreshRevokeTokens: No valid admin token credential
Post "https://default-keystone:30357/v3/auth/tokens": dial tcp: lookup default-keystone on 10.96.0.10:53: read udp 10.40.136.8:60762->10.96.0.10:53: read: connection refused
[error 2024-12-12 16:06:29 auth.(*authManager).authAdmin(auth.go:269)] Admin auth failed: {"error":{"class":"DNSError","code":499,"details":"Post \"https://default-keystone:30357/v3/auth/tokens\": dial tcp: lookup default-keystone on 10.96.0.10:53: read udp 10.40.136.8:60762->10.96.0.10:53: read: connection refused","request":{"body":"{\"auth\":{\"context\":{\"source\":\"srv\"},\"identity\":{\"methods\":[\"password\"],\"password\":{\"user\":{\"domain\":...ult\"},\"name\":\"system\"}}}}","headers":{"Content-Length":"241","Content-Type":"application/json","User-Agent":"yunioncloud-go/201708","X-Yunion-Parent-Id":"","X-Yunion-Peer-Service-Name":"cloudid","X-Yunion-Remote-Addr":"default-keystone:30357","X-Yunion-Span-Id":"0","X-Yunion-Span-Name":"","X-Yunion-Strace-Debug":"true","X-Yunion-Strace-Id":"36593ae3"},"method":"POST","url":"https://default-keystone:30357/v3/auth/tokens"}}}
goroutine 1 [running]:
runtime/debug.Stack()
        /usr/lib/go/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
        /usr/lib/go/src/runtime/debug/stack.go:16 +0x13
yunion.io/x/log.Fatalf({0x4ee5200, 0x19}, {0xc001447d28, 0x1, 0x1})
        /root/go/src/yunion.io/x/onecloud/vendor/yunion.io/x/log/log.go:138 +0x2c
yunion.io/x/onecloud/pkg/mcclient/auth.AsyncInit(0xc000e56300, 0x0?, 0x0?, {0xc000d154c0, 0x0?}, {0xc000d15500, 0x4969f20?}, 0x0)
        /root/go/src/yunion.io/x/onecloud/pkg/mcclient/auth/auth.go:448 +0xde
yunion.io/x/onecloud/pkg/mcclient/auth.Init(...)
        /root/go/src/yunion.io/x/onecloud/pkg/mcclient/auth/auth.go:455
yunion.io/x/onecloud/pkg/cloudcommon/app.InitAuth(0x79385c0, 0x4fe39e8)
        /root/go/src/yunion.io/x/onecloud/pkg/cloudcommon/app/auth.go:75 +0x3f9
yunion.io/x/onecloud/pkg/cloudid/service.StartService()
        /root/go/src/yunion.io/x/onecloud/pkg/cloudid/service/service.go:51 +0x85
main.main()
        /root/go/src/yunion.io/x/onecloud/cmd/cloudid/main.go:22 +0xf
[fatal 2024-12-12 16:06:29 auth.AsyncInit(auth.go:448)] Auth manager init err: authAdmin: {"error":{"class":"DNSError","code":499,"details":"Post \"https://default-keystone:30357/v3/auth/tokens\": dial tcp: lookup default-keystone on 10.96.0.10:53: read udp 10.40.136.8:60762->10.96.0.10:53: read: connection refused","request":{"body":"{\"auth\":{\"context\":{\"source\":\"srv\"},\"identity\":{\"methods\":[\"password\"],\"password\":{\"user\":{\"domain\":...ult\"},\"name\":\"system\"}}}}","headers":{"Content-Length":"241","Content-Type":"application/json","User-Agent":"yunioncloud-go/201708","X-Yunion-Parent-Id":"","X-Yunion-Peer-Service-Name":"cloudid","X-Yunion-Remote-Addr":"default-keystone:30357","X-Yunion-Span-Id":"0","X-Yunion-Span-Name":"","X-Yunion-Strace-Debug":"true","X-Yunion-Strace-Id":"36593ae3"},"method":"POST","url":"https://default-keystone:30357/v3/auth/tokens"}}}
[root@master1 ~]# 
```

**Comment by wanyaoqi** [comment]
default-etcd 起不来一般是网络问题，etcd init 容器会检测容器 dns是否可用。你可以看看你的kube-system下网络组件是否正常

**Comment by chenjacken** [comment]
> default-etcd 起不来一般是网络问题，etcd init 容器会检测容器 dns是否可用。你可以看看你的kube-system下网络组件是否正常
有些POD不是运行在3台master上，我试试启动对应的计算节点服务器（之前关机了）。
kube-system下pod状态

```
[root@master1 ~]# kubectl get pods -n kube-system -owide
NAME                                       READY   STATUS        RESTARTS        AGE   IP              NODE       NOMINATED NODE   READINESS GATES
calico-kube-controllers-7d9768dc46-9qxfs   1/1     Terminating   0               8d    10.40.132.1     ser-b1-4   <none>           <none>
calico-kube-controllers-7d9768dc46-wx58w   1/1     Running       0               7d    10.40.9.75      ser-b5-4   <none>           <none>
calico-node-2tx9z                          1/1     Running       2 (8d ago)      25d   172.16.2.43     ser-b8-3   <none>           <none>
calico-node-nwncn                          1/1     Running       6 (20h ago)     27d   172.16.2.12     master2    <none>           <none>
calico-node-p89bv                          1/1     Running       4 (8d ago)      25d   172.16.2.41     ser-b8-1   <none>           <none>
calico-node-pntwk                          1/1     Running       8 (20h ago)     27d   172.16.2.11     master1    <none>           <none>
calico-node-r96v2                          1/1     Running       2 (8d ago)      25d   172.16.2.44     ser-b8-4   <none>           <none>
calico-node-tkkrh                          1/1     Running       2 (8d ago)      25d   172.16.2.39     ser-b7-5   <none>           <none>
calico-node-xg2pl                          1/1     Running       6 (19h ago)     27d   172.16.2.13     master3    <none>           <none>
coredns-6799fbcd5-jnv4k                    1/1     Running       0               8d    10.40.204.129   ser-b1-6   <none>           <none>
helm-install-traefik-fpllt                 0/1     Completed     0               15m   10.40.136.52    master3    <none>           <none>
keepalived-master1                         1/1     Running       17 (20h ago)    27d   172.16.2.11     master1    <none>           <none>
keepalived-master2                         1/1     Running       14 (20h ago)    27d   172.16.2.12     master2    <none>           <none>
keepalived-master3                         1/1     Running       14 (19h ago)    27d   172.16.2.13     master3    <none>           <none>
local-path-provisioner-84db5d44d9-89rzt    1/1     Running       0               8d    10.40.9.1       ser-b2-6   <none>           <none>
metrics-server-67c658944b-mfvhg            1/1     Terminating   0               8d    10.40.110.129   ser-b2-4   <none>           <none>
metrics-server-67c658944b-wz4bf            0/1     Pending       0               7d    <none>          ser-b5-4   <none>           <none>
traefik-2n99d                              1/1     Running       6 (20h ago)     27d   172.16.2.12     master2    <none>           <none>
traefik-kn6pg                              1/1     Running       7 (20h ago)     27d   172.16.2.11     master1    <none>           <none>
traefik-rdxpb                              1/1     Running       6 (19h ago)     27d   172.16.2.13     master3    <none>           <none>
[root@master1 ~]# 
```

**Comment by wanyaoqi** [comment]
calico-kube-controllers nodeAffinity label 是 onecloud.yunion.io/controller=enable
kubectl get nodes -o wide --show-lables 看下master 节点是否有这个 label

**Comment by chenjacken** [comment]
收到，已解决
